fastly/js-compute-runtime

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
As reported in #7, under certain circumstances we throw an internal error when calling `Headers#delete` with a non-existent header name. This only happens if the `Headers` object is associated with a `Request` or `Response`, and is caused by the hostcall we use to mirror the change to the host.
With this change, we only do the hostcall if the named header exists.
Fixes #7
(Comment updated to fix the backtick-enclosed terms my shell stripped, and to more accurately describe what this change does.)
> Don't trap when trying to delete a non-existent header

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
I do wish C++ had proper error handling :/
> Check return value of Request::create in fetch

- src/main.rs
One more for the "we really need a better testing story to catch things before integration into the internal SDK CI system." :/
> Correctly preopen the current directory in the Wizer config

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
When a `fetch` request fails with a network error (e.g. because the host isn't reachable), we need to properly reject the pending promise for the request, instead of attempting to work with the invalid handle the host returned.
> Reject fetch promise on network error

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
... instead of just unceremoniously aborting the service.
> Error the ReadableStream when a body read fails in the hostcall

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
When using existing libraries, it can be difficult to pass in the backend to use in `fetch`. With this change, it's possible to define a default backend to use when none is passed in to the `fetch` call.
Note that this isn't ideal in situations where multiple backends are used. An alternative that's been discussed is to derive the backend from the request URL's host name instead. We might do that before the next SDK release.
In the meantime, this helps get WPT tests running — see the next PR.
> Enable defining a default backend using `fastly.defaultBackend`

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
This only returns `null` when the key is missing and still throws when the dictionary itself isn't found. We should catch the latter in `new Dictionary()`, but that's for another patch.
Fixes #37
> Return null instead of throwing on missing key in `Dictionary#get`

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
C@E [exposes various pieces of information about the service and host as environment variables](https://developer.fastly.com/reference/compute/ecp-env/). This patch adds an official way to read those variables.
The patch also removes the previous, undocumented way this information was exposed, as more discussion lead to the consensus that this approach makes more sense.
> Implement `fastly.env.get` as a way to read environment variables

- .github/workflows/main.yml
- Cargo.lock
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
These are some small changes I amassed in working on TransformStream that were easy to separate out, so I moved them into a separate pull request for easier reviewing.
> Loose set of small fixes and improvements

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
This PR contains a smattering of smaller builtins, and some improvements to the behavior of existing ones. They're small enough in sum that I didn't feel it makes sense to split them into multiple PRs, but let me know if you disagree.
Stacked on #64, so the first two commits don't need reviewing.
> Set of added or improved smaller builtin objects/functions

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- Ensure that headers are correctly applied from the `input` argument to `new Request`
- Ensure that `cacheOverride` is correctly applied from the `input` argument to `new Request`
- Ensure that the backend is correctly applied from the `input` argument to `new Request`
- Handle `xqd_body_write` errors in a DEBUG build-safe way. (The issue is that we're using a non-GC safe reference to a raw buffer underlying an ArrayBuffer, which requires emplacing a DEBUG `JS::AutoCheckCannotGC` guard. There never were any GC-safety issues because at the moment we're potentially GCing, we're not using the unsafe reference anymore.)
> Fix various bugs in Request and Response handling

- c-dependencies/js-compute-runtime/Makefile
Add the fix for the `DEBUG` variable mentioned in #78.
> Add the suggestion from #78

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- integration-tests/js-compute/package-lock.json
- sdk/js-compute/package-lock.json
- sdk/js-compute/package.json
Preparing the version 0.3.0 release.
> Prepare version 0.3.0

- sdk/js-compute/package.json
Also bump the `js-compute-runtime-version` field to match the `version` field.
> chore: Add the repository field to package.json

- tests/wpt-harness/expectations/WebCryptoAPI/getRandomValues.any.js.json
- tests/wpt-harness/expectations/compression/compression-bad-chunks.tentative.any.js.json
- tests/wpt-harness/expectations/compression/compression-including-empty-chunk.tentative.any.js.json
- tests/wpt-harness/expectations/compression/compression-multiple-chunks.tentative.any.js.json
- tests/wpt-harness/expectations/compression/compression-output-length.tentative.any.js.json
- tests/wpt-harness/expectations/encoding/idlharness.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/request-upload.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/request-upload.h2.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/scheme-about.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-error.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-headers.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-init-stream.any.js.json
- tests/wpt-harness/expectations/html/webappapis/structured-clone/structured-clone.any.js.json
The steps I took to do this were:
```sh
git submodule update --recursive --init
(cd c-dependencies/spidermonkey/ && ./download-engine.sh release)
(cd tests/wpt-harness/wpt && git fetch && git switch master && git pull)
(mkdir -p dist && cd dist && make -f ../c-dependencies/js-compute-runtime/Makefile && bash ../tests/wpt-harness/build-wpt-runtime.sh && node ../tests/wpt-harness/run-wpt.mjs -vv --update-expectations)
git add . && git commit -m 'update to latest web-platform-tests and update our test results'
```
> update to latest web-platform-tests and update our test results

- .github/workflows/dependencies.yml
these were approved in this ticket -> https://fastly.atlassian.net/browse/LAW-4337
> allow isc and BSD-2

- c-dependencies/js-compute-runtime/builtins/console.cpp
- integration-tests/js-compute/fixtures/console/bin/index.js
- integration-tests/js-compute/fixtures/console/fastly.toml.in
- integration-tests/js-compute/fixtures/console/tests.json
This gets us closer to following the spec at https://console.spec.whatwg.org/#logger
>  allow arbitrary amount of parameters passed to the console methods 

- c-dependencies/js-compute-runtime/builtins/fastly.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
Add issue references in source for performance issues.
> chore: Add issue references

- sdk/js-compute/index.d.ts
- sdk/js-compute/package-lock.json
- sdk/js-compute/package.json
- sdk/js-compute/tsconfig.json
The version of typedoc we are using no longer has the minimal theme as it is very out of date and buggy.
I've installed a new theme which is similar to minimal but offers some extra features such as search.
I've also fixed some broken internal linking we had in the api docs
> update our api website theme

- sdk/js-compute/index.d.ts
- sdk/js-compute/index.test-d.ts
0.5.0 updated the console methods such as log to accept any number of arguments.
This PR updates the TypeScript definitions for these methods and also updates the comment that describes them.
> Console types

- sdk/js-compute/CHANGELOG.md
- sdk/js-compute/package-lock.json
- sdk/js-compute/package.json
this release includes:
- dynamic backends support
- config-store support
- deprecation note for dictionary and recommendation to move to config-store
> release 0.5.4

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/request-cache-key/bin/index.js
> fix: ensure custom cache keys are uppercased

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/request-upstream/bin/index.js
- integration-tests/js-compute/fixtures/request-upstream/tests.json
fixes https://github.com/fastly/js-compute-runtime/issues/352
>  fix: do not free the method_str.ptr as we still require the memory 

- .github/actions/e2e/action.yml
- .github/workflows/main.yml
Bump action versions to avoid node12 deprecation.
> chore: Bump action versions

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Remove an unused overload of `read_from_handle_all`.
> chore: Remove an unused function

- c-dependencies/js-compute-runtime/builtins/crypto.cpp
- c-dependencies/js-compute-runtime/builtins/crypto.h
- documentation/docs/globals/crypto/randomUUID.mdx
- tests/wpt-harness/expectations/WebCryptoAPI/randomUUID.https.any.js.json
- tests/wpt-harness/tests.json
This was fun to implement and also, having web-platform-tests is so helpful!
> feat: add crypto.randomUUID function and corresponding documentation

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Rework `read_from_handle_all` to avoid realloc'ing for each chunk read. Additionally use unique_ptr to avoid needing any explicit uses of `JS_free`, ensuring that we free memory no matter which path we take when returning.
> Refactor read_from_handle_all

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/xqd-world/xqd_world.c
- c-dependencies/js-compute-runtime/xqd-world/xqd_world.h
- c-dependencies/js-compute-runtime/xqd.wit
- Content encodings should be a `flags`
- Re-generate the xqd world
> content-encodings should be a flags

- c-dependencies/js-compute-runtime/builtins/fastly.cpp
- c-dependencies/js-compute-runtime/builtins/object-store.cpp
- c-dependencies/js-compute-runtime/builtins/url.cpp
- c-dependencies/js-compute-runtime/builtins/url.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Switch the URL builtin over to using the builtin class instead.
> refactor: Migrate URL to the builtin class

- .vscode/settings.json
- c-dependencies/js-compute-runtime/builtins/crypto-algorithm.cpp
- c-dependencies/js-compute-runtime/builtins/crypto-algorithm.h
- c-dependencies/js-compute-runtime/builtins/crypto-key.cpp
- c-dependencies/js-compute-runtime/builtins/crypto-key.h
- c-dependencies/js-compute-runtime/builtins/subtle-crypto.cpp
- c-dependencies/js-compute-runtime/builtins/subtle-crypto.h
- integration-tests/js-compute/fixtures/crypto/bin/index.js
- tests/wpt-harness/expectations/WebCryptoAPI/idlharness.https.any.js.json
With this and previous crypto work, we can import a key and create a signature for some data with the key like so:
```js
// From https://www.rfc-editor.org/rfc/rfc7517#appendix-A.2
const privateJsonWebKeyData = {
"alg":"RS256",
"d":"X4cTteJY_gn4FYPsXB8rdXix5vwsg1FLN5E3EaG6RJoVH-HLLKD9M7dx5oo7GURknchnrRweUkC7hT5fJLM0WbFAKNLWY2vv7B6NqXSzUvxT0_YSfqijwp3RTzlBaCxWp4doFk5N2o8Gy_nHNKroADIkJ46pRUohsXywbReAdYaMwFs9tv8d_cPVY3i07a3t8MN6TNwm0dSawm9v47UiCl3Sk5ZiG7xojPLu4sbg1U2jx4IBTNBznbJSzFHK66jT8bgkuqsk0GjskDJk19Z4qwjwbsnn4j2WBii3RL-Us2lGVkY8fkFzme1z0HbIkfz0Y6mqnOYtqc0X4jfcKoAC8Q",
"dp":"G4sPXkc6Ya9y8oJW9_ILj4xuppu0lzi_H7VTkS8xj5SdX3coE0oimYwxIi2emTAue0UOa5dpgFGyBJ4c8tQ2VF402XRugKDTP8akYhFo5tAA77Qe_NmtuYZc3C3m3I24G2GvR5sSDxUyAN2zq8Lfn9EUms6rY3Ob8YeiKkTiBj0", …
```
> feat: Implement subset of crypto.subtle.sign which can sign data with a JSONWebKey using RSASSA-PKCS1-v1_5

- c-dependencies/js-compute-runtime/builtins/crypto-key.cpp
- c-dependencies/js-compute-runtime/builtins/crypto-key.h
- c-dependencies/js-compute-runtime/builtins/subtle-crypto.cpp
- c-dependencies/js-compute-runtime/builtins/subtle-crypto.h
- integration-tests/js-compute/fixtures/crypto/bin/index.js
- integration-tests/js-compute/fixtures/crypto/tests.json
- tests/wpt-harness/expectations/WebCryptoAPI/idlharness.https.any.js.json
With this, we have all the methods in place for JWT usage in JS for Fastly Compute :D
>  feat: Implement subset of crypto.subtle.verify which can verify a signature with a JSONWebKey using RSASSA-PKCS1-v1_5

- types/index.d.ts
> fix: add fastly:secret-store types

- CHANGELOG.md
Also added redirect so this is no longer broken but better to avoid link rot
> Fix broken link

- documentation/docs/index.mdx
A fairly extensive effort here to help people who may have found themselves on the js-compute reference a bit early in their C@E journey, which is a problem we're finding in workshops.
Could be a good opportunity here to add a section of known issues / limitations maybe, like which bits of crypto we don't have yet?  But I think this is a decent starting point.
> Revamp overview page of docs

- package.json
- yarn.lock
> chore: Update jco

- runtime/js-compute-runtime/js-compute-runtime.cpp
This release includes:
- An optimization for functions that only use `arguments.length` to avoid allocating the `arguments` object.
- An optimization for `Object.HasOwn` which for small numbers of atoms just unrolls the loop.
> feat: update to SpiderMonkey 124.0.2

- .github/workflows/main.yml
- .github/workflows/release-please.yml
- ci/format-changelog.js
- package.json
- yarn.lock
Inlines the changelog checker, updating it to format the changelog as necessary.
> actions: automatically reformat changelog

- .github/actions/e2e/action.yml
- .github/workflows/main.yml
- runtime/fastly/builtins/fetch/request-response.cpp
- runtime/js-compute-runtime/builtins/request-response.cpp
This fixes and tests the debug build against the SDK integration test suite.
Some assertions are no longer valid and need to be disabled since the KV store work shared these methods for KV store objects.
> fix: debug build & tests

- .github/workflows/main.yml
this will unblock https://github.com/fastly/js-compute-runtime/pull/817
> update to latest version of viceroy

- runtime/fastly/host-api/host_api.cpp
Adds some missing `cabi_free` calls for the error paths in host call operations.
> add missing cabi_free calls

- documentation/docs/globals/Headers/prototype/getSetCookie.mdx
Adds the documentation for the recently added method.
> docs: add getSetCookie documentation

- .github/workflows/main.yml
- documentation/docs/backend/Backend/Backend.mdx
- integration-tests/js-compute/fixtures/app/src/compute.js
- integration-tests/js-compute/fixtures/app/src/dynamic-backend.js
- integration-tests/js-compute/fixtures/app/src/index.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/backend.cpp
- runtime/fastly/builtins/backend.h
- runtime/fastly/host-api/fastly.h
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
- types/backend.d.ts
This adds support for the `grpc` backend configuration option.
Resolves #943.
> feat: grpc backend option

- runtime/fastly/builtins/fastly.cpp
- src/compileApplicationToWasm.js
Updatest to the latest StarlingMonkey & Weval, refactoring to use the new runtime configuration system.
> deps: update to latest StarlingMonkey

- test-d/compute.test-d.ts
- types/compute.d.ts
> fix: typing file for compute builtin

- .github/workflows/main.yml
- runtime/fastly/host-api/fastly.h
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
Issue: https://github.com/fastly/js-compute-runtime/issues/1029
> KVStore lookup fix for if-generation-match using lookup-wait-v2

- .github/workflows/main.yml
- integration-tests/js-compute/fixtures/module-mode/src/kv-store.js
- integration-tests/js-compute/fixtures/module-mode/tests.json
- integration-tests/js-compute/setup.js
- integration-tests/js-compute/test.js
This should fix the skip flags that we added to CI for the multi-test running, avoiding some CI bugs.
> ci adjustments

- src/compileApplicationToWasm.js
- types/index.d.ts
This fixes a stack overflow bug with Weval by increasing the rust stack size.
> fix: Weval stack overflow bug

- integration-tests/js-compute/fixtures/app/src/headers.js
- integration-tests/js-compute/fixtures/app/tests.json
- types/globals.d.ts
https://github.com/fastly/js-compute-runtime/issues/1155
> fix: TypeScript declaration for Headers (#1155)

- runtime/fastly/builtins/html-rewriter.cpp
If the HTML document is large enough, processing is split over a GC collection, and some of the variables are not rooted, causing use-after-frees.
> fix: Root HTML rewriter variables to ensure no GC
