- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
This introduces three significant changes:
1. Support multiple `"fetch"` event handlers instead of just one
2. Support `Promise<Response>` in addition to `Response` in `FetchEvent#respondWith`
3. Require `FetchEvent#respondWith` to be called synchronously from within a `"fetch"` handler
This last one is a breaking change: before, we supported invoking `respondWith` at any point. That isn't what the spec wants us to do, and it also means that we don't have a good way to determine when a `FetchEvent` has been fully handled. Our previous solution to that was to wait until all pending tasks have been completed, but that can potentially mean running an instance for much longer than the author intended.
> Make FetchEvent handling more spec-compliant

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Turns out `--allow-undefined` isn't necessary, and removing it means the linker doesn't emit imports from the `env` namespace for undefined symbols.
It also turns out that since the update to a Spidermonkey compiled with Rust 1.54.0, we weren't producing working binaries: the builds were importing a symbol (`mozalloc_abort`) from `env`, which is what happens with `--allow-undefined` if a symbol isn't found. I hadn't realized this problem because I did all my testing under Wizer, which is fine with unknown builtins as long as they aren't called.
This change will prevent bugs like this going forward, but we also clearly need a better testing story. I have a plan for that, but it's for another day.
> Link without --allow-undefined

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
These features are stable and enabled in Firefox by default, but not in Spidermonkey's default configuration, so we have to manually enable them.
(Depends on #12, so only the last patch is relevant here.)
> Enable private class fields and methods, plus ergonomic brand checks

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
Before this patch, we always kept the service running until all async tasks had been processed. That can result in services running longer than expected though, e.g. when a "fire-and-forget" logging task is implemented using `fetch`.
The ServiceWorkers spec defines the `FetchEvent`'s lifetime to include resolution of any (potentially async) results passed to `FetchEvent#respondWith`, and of any promises passed to `FetchEvent#waitUntil`.
With this patch, we shut down the service as soon as the `FetchEvent`'s lifetime has ended. E.g., the following code will trigger a backend request, wait until it has returned, and send it on as a response:
```js
addEventListener("fetch", event => {
event.respondWith(fetch("http://example.com", { backend: "example_backend" }));
});
```
This code however …
> Implement FetchEvent#waitUntil

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
The fetch spec [requires uppercasing](https://fetch.spec.whatwg.org/#concept-method-normalize) for exactly 6 HTTP method names, but not any others 🙃
Fixes #9
> Normalize HTTP method names when constructing Requests

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
Since #14, we don't by default keep the service active until all async operations have completed. Instead, it's only kept active until a response has been sent and all promises passed to `FetchEvent#waitUntil` have settled.
However, that meant that by default we'd shut the service down while responses are streaming, which will of course not do. So this patch changes things to treat the `FetchEvent` as active during response streaming as well.
> Extend FetchEvent lifetime to include response streaming

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/xqd.h
C@E nowadays has a dedicated hostcall for geo lookups, and we should use it.
> Use fastly_geo::lookup hostcall instead of API http request

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
Before this patch, we mostly just silently pretend that things worked because the hostcall stubbed by wizer just returns `0`. To prevent things going awry after deployment and in hard-to-fathom ways, ensure that we catch any attempts to call/construct affected builtins during the initialization phase.
Fixes #3 
(Stacked on #18 to make use of `FetchEvent::instance()`)
> Mark builtins that rely on hostcalls as request-handler-only

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- src/main.rs
It's often desirable to be able to embed binary assets into a wasm file. Eventually we'll have a standardized way to do so, but for now we don't.
This patch thus adds `fastly.includeBytes` as the moral equivalent to Rust's [include_bytes!](https://doc.rust-lang.org/1.54.0/std/macro.include_bytes.html) macro. `includeBytes` can only be used during the initialization/wizening phase, because that's the only time filesystem is (through the one-line change in `src/main.rs`) available.
The way binary data is embedded is pretty close to optimal: the data is without any intermediate copies placed into a buffer underlying the `Uint8Array` that `includeBytes` returns. That way, the data is part of the wizer snapshot without any overhead.
Making full use of these included assets requires the ability …
> Add support for including binary files, and for using typed arrays as `Response` bodies

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Added more meaningful messages to hostcall errors
The mapping from error code number to message comes from https://docs.rs/fastly-shared/0.6.3/src/fastly_shared/lib.rs.html#35-96
Resolves https://github.com/fastly/js-compute-runtime/issues/11
> Improve handling of hostcall errors

- c-dependencies/js-compute-runtime/rust-url/Cargo.toml
- c-dependencies/js-compute-runtime/rust-url/src/lib.rs
Also preserve debug info in release builds of rust-url to ease debugging. We strip all debug info for release builds of the runtime post-linking anyway.
This isn't of major importance, but fixes a spec compliance issue found through running WPT tests.
> Strip leading `?` in `URLSearchParams` constructor

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
When changing Geolocation lookups to using the hostcall, I didn't correctly translate inputs to the required format—octet bytes instead of a string representation. This commit fixes that.
Fixes #42
> Fix geo-lookup hostcall invocation

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
Until now, we only fully initialized the downstream request object when it's retrieved by script, i.e. when the `FetchEvent#request` accessor was invoked. However, since #38, we're resolving relative URLs based on the downstream request's URL, and hence need to ensure that it's initialized properly.
All tests I ran before trying to publish a new SDK, and hence running the full test suite, happened to invoked the accessor, so I didn't realize that things weren't working without doing so.
This patch fixes things, and also lightly improves some aspects of base URL handling I found while debugging this.
> Always fully initialize the downstream Request

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Note: I had previously published version 0.3.0, but given that there are no breaking changes here, and that the previously published version was somewhat broken, I'm retracting that and only bumping the minor version here instead.
> Update changelog and Cargo.toml to version 0.2.2

- .github/workflows/main.yml
- CHANGELOG.md
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
This change removes a single line that caused us to keep the service around after the client response was successfully sent if there are any async tasks pending. The latter should only happen if the promises for any pending async tasks were passed to `FetchEvent#waitUntil`.
> Avoid waiting for async tasks that weren't passed to `FetchEvent#waitUntil`

- .github/workflows/main.yml
- .gitignore
- .vscode/c_cpp_properties.json
- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
SpiderMonkey doesn't have a `TransformStream` implementation, and doing a proper one that'd work for Firefox as well would be a huge amount of work. So instead, we're adding our own implementation, using SpiderMonkey's `ReadableStream` and `WritableStream` implementations.
The goal is for the implementation to be safe, efficient, and spec-compliant, so we're not taking undue shortcuts here. The difference between this and an in-SpiderMonkey implementation is that we don't have to worry about multiple compartments and different kinds of cross-compartment wrappers, which simplifies the implementation significantly.
The implementation passes almost all spec tests (CI support for which will be added in a separate PR), and is I think reasonably efficient.
> Implement TransformStream

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
This PR adds support for detecting when a Request or Response's body stream is piped to another Request or Response's body via a TransformStream. In that case, instead of reading every chunk from the body individually and then writing it to the destination body, we use the `xqd_body_append` hostcall to append the entire body in one go.
In situations where multiple bodies are piped to the same destination, this reduces the complexity from O(number of streams * number of chunks per stream) to O(number of streams), which in most cases basically takes JS execution out of the equation.
> Support directly piping entire body streams to Request or Response objects instead of copying them by the chunk

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
This pair of commits contains a ton of small changes to `Request` and `Response` objects to make them more spec compliant, with key aspects being
- spec-compliant constructors, enabling proper application of properties on the `input` and `init` arguments
- support for `URLSearchParams` as bodies
- support for content-provided bodies in `{Request,Response}.{text,json,arrayBuffer}()`
The diff is pretty big, but many of the added lines are just comments documenting the spec steps implemented, so I hope it won't be too annoying to review.
> Significantly improve spec-compliance of Request and Response objects

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/xqd.h
Upon testing I have found the default c@e js runtime limit is 4k for headers. This causes issues with larger cookie and other headers. 
The attached update changes the limit to 69K and switches around the validation for other limits to be based off the header limit rather than the dictionary limit.
Successful call with 9k header with viceroy
```
Jan 05 14:48:31.842  INFO request{id=1}: handling request GET http://127.0.0.1:7878/
Log: headers
Log: host length is 14 127.0.0.1:7878
Log: connection length is 10 keep-alive
Log: cache-control length is 9 max-age=0
Log: sec-ch-ua length is 64 " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
Log: sec-ch-ua-mobile length is 2 ?0
Log: sec-ch-ua-platform length is 9 "Windows"
Log: upgrade-insecure-requests length is 1 1
Log: …
```
> updating header to match vcl max header length

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/xqd.h
At time of writing, the maximum uri allowed on fastly is 8kb -- https://docs.fastly.com/en/guides/resource-limits
I came across this issue when replaying production traffic from https://poyfill.io onto our js compute-at-edge implementation, which is currently running on https://qa.polyfill.io
> increase max uri length to 8k to match the limit documented on https://docs.fastly.com/en/guides/resource-limits

- .github/actions/binary-compatible-builds/README.md
- .github/actions/binary-compatible-builds/action.yml
- .github/actions/binary-compatible-builds/main.js
- .github/actions/github-release/package.json
- .github/workflows/main.yml
This PR implements the [Binary Compatible Builds Github Action from Wasmtime](https://github.com/bytecodealliance/wasmtime/tree/main/.github/actions/binary-compatible-builds). 
This allows us to execute the `js-compute-runtime` in Ubuntu 16, for our old Docker containers, or any extended security release linux users 😄 
**NOTE:** The publishing job hasn't been tested, but all the artifacts are correctly added ([old build example](https://github.com/fastly/js-compute-runtime/actions/runs/2186969757)), so this should in theory work 😅
> Create more compatible binaries for all supported platforms

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
previously this error message said "Request constructor", which was misleading as this error is within the Response constructor.
I've used the same error message text as Firefox does.
We could modify the error message some more to mention which status codes are 'null body' statuses, as a null body status is a status that is 101, 204, 205, or 304, and the user reading the error message may not know what is meant by `null body status`.
> Change error message which is given when constructing a Response instance with a body and a null body status

- .github/workflows/main.yml
- ci/build-tarballs.sh
- ci/shellcheck.sh
- tests/wpt-harness/build-wpt-runtime.sh
Add a new build step to run shellcheck on all tracked `*.sh` files, and apply shellcheck suggestions to existing scripts.
> Run shellcheck in CI

- .gitignore
- c-dependencies/js-compute-runtime/.gitignore
- c-dependencies/js-compute-runtime/Makefile
Add a new `compile_commands.json` target in `c-dependencies/js-compute-runtime/Makefile` for generating  the build config that `clangd` requires. Typing `make compile_commands.json` will generate the file, and enable the use of `clangd` when working on `js-compute-runtime`.
Also make some small changes to the `Makefile`:
* Replace uses of `=` with `:=` when possible to avoid accidentally introducing macros
* Add `clean` and `distclean` targets
* Add entries for generated intermediates to `.gitignore`
> Add support for generating a compile_commands.json for c-dependencies/js-compute-runtime

- README.md
Updating the readme to make it easier for new developers to compile the library.
An update to PR #57 and fixes #56.
> Updating the readme doc

- .vscode/c_cpp_properties.json
- c-dependencies/js-compute-runtime/Makefile
Because no specific shell was set in the Makefile it defaults to /bin/sh which has a built-in version of echo that does not accept the -n option and instead will write -n to stdout.
Setting the shell to /bin/bash means we will use bash and bashs's built-n echo which does support the -n option, which means we will start generating a valid JSON file for compile_commands.json
> Fix `make compile_commands.json` and add to vscode project settings

- .github/workflows/main.yml
To speed up builds, cache compiled dependencies in the build step using https://github.com/Swatinem/rust-cache. Always rebuild on the `main` branch and for release tags.
As a follow-on from this, we'll need to change our `binary-compatible-builds` action to expose the `~/.cargo` directory outside of the centos container it runs in, as that directory currently disappears with the centos container that runs the linux build.
> Cache crate dependencies on branches

- c-dependencies/js-compute-runtime/rust-url/Cargo.toml
Currently we are including the full debug information inside the binary.
This patch changes the release profile to use the default debug value of `false` which will include no debug information inside the binary.
References:
- The default release profile values: https://doc.rust-lang.org/cargo/reference/profiles.html#release
- What the debug value is used for: https://doc.rust-lang.org/cargo/reference/profiles.html#debug
> Do not include debug information when compiling rust-url in release mode

- .gitignore
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/extend-from-request/extend-from-request.ts
- integration-tests/js-compute/fixtures/extend-from-request/fastly.toml
- integration-tests/js-compute/sdk-test-config.json
This is part of the solution for https://github.com/fastly/js-compute-runtime/issues/113 - that issue shows that all our built-in classes are not extendable within applications' JavaScript.
This pull-request changes our Request to use `JS_NewObjectForConstructor` when the construction has come from the applications' JavaScript, which assigns the correct prototype to the instance being constructed (taking into account `extends` in JavaScript)
I've also added a test which confirms that the correct prototype has been assigned when extending from `Request`
> Allow classes to extend from Request

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/extend-from-builtins/extend-from-builtins.ts
- integration-tests/js-compute/fixtures/extend-from-builtins/fastly.toml
- integration-tests/js-compute/sdk-test-config.json
- tests/wpt-harness/expectations/streams/transform-streams/general.any.js.json
This pull-request changes our TransformStream implementation to use JS_NewObjectForConstructor when the construction has come from the applications' JavaScript, which assigns the correct prototype to the instance being constructed (taking into account extends in JavaScript)
I've also added a test which confirms that the correct prototype has been assigned when extending from TransformStream, the test is written in a way that makes it simpler to add the same test for any other builtin classes
> Allow TransformStream to be used as a base class to extend from within application javascript

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/extend-from-builtins/extend-from-builtins.ts
This pull-request changes our CompressionStream implementation to use JS_NewObjectForConstructor when the construction has come from the applications' JavaScript, which assigns the correct prototype to the instance being constructed (taking into account extends in JavaScript)
I've also added a test which confirms that the correct prototype has been assigned when extending from CompressionStream, the test is written in a way that makes it simpler to add the same test for any other builtin classes
> Allow CompressionStream to be used as a base class to extend from within application javascript

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/extend-from-builtins/extend-from-builtins.ts
This pull-request changes our Dictionary implementation to use JS_NewObjectForConstructor when the construction has come from the applications' JavaScript, which assigns the correct prototype to the instance being constructed (taking into account extends in JavaScript)
I've also added a test which confirms that the correct prototype has been assigned when extending from Dictionary, the test is written in a way that makes it simpler to add the same test for any other builtin classes
> Allow Dictionary to be used as a base class to extend from within application javascript

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/extend-from-builtins/extend-from-builtins.ts
This pull-request changes our URLSearchParams implementation to use JS_NewObjectForConstructor when the construction has come from the applications' JavaScript, which assigns the correct prototype to the instance being constructed (taking into account extends in JavaScript)
I've also added a test which confirms that the correct prototype has been assigned when extending from URLSearchParams, the test is written in a way that makes it simpler to add the same test for any other builtin classes
> Allow URLSearchParams to be used as a base class to extend from within application javascript

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/extend-from-builtins/extend-from-builtins.ts
This pull-request changes our Headers implementation to use JS_NewObjectForConstructor when the construction has come from the applications' JavaScript, which assigns the correct prototype to the instance being constructed (taking into account extends in JavaScript)
I've also added a test which confirms that the correct prototype has been assigned when extending from Headers, the test is written in a way that makes it simpler to add the same test for any other builtin classes
> Allow Headers to be used as a base class to extend from within application javascript

- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
It took a while to track down what it is that ensures we're disabling lazy function compilation, and I wanted to preserve that information in a comment :)
> Add a comment explaining why we use `setForceFullParse`

- integration-tests/js-compute/fixtures/extend-from-builtins/extend-from-builtins.ts
The relevant changes to allow `Request` to be extended have been made, so we can un-comment its test case in the extend-from-base test.
> Uncomment the Request subclass test

- integration-tests/js-compute/run-all.sh
Make it easier to run the integration tests locally by adding a script to wrap running the github action.
> Add a script to run all integration tests

- .github/actions/compute-sdk-test/main.js
- .github/actions/compute-sdk-test/src/test-suite.js
In order to make the compute-sdk-test action reusable for other sdks, and to wrangle its current complexity, this PR adds a class to track configuration information and plumbs it through the tests. The next step will be to break up the test running logic in `main.js` so that it's possible to run one test at a time.
> Add a class to manage integration test configuration

- .github/workflows/main.yml
When working on a branch, I sometimes make frequent pushes to github. Currently the each push will cause our CI test to run for the push, which means if 3 pushes happened, 3 runs of CI would happen.
This pull request configures the workflow to go and cancel any previously running workflows of the same name on the same branch. What this means is if 3 pushes happened, the first 2 runs of CI would get cancelled and only the last run would happen.
> cancel any previously running test run for the same branch

- .github/workflows/main.yml
GitHub's version works across several package ecosystems and also
supports checking the licenses of dependencies.
> Replace cargo-audit with GitHub's dependency-review

- integration-tests/js-compute/build-one.sh
- integration-tests/js-compute/fixtures/includeBytes/fastly.toml.in
- integration-tests/js-compute/fixtures/includeBytes/includeBytes.ts
- integration-tests/js-compute/fixtures/includeBytes/message.txt
- integration-tests/js-compute/fixtures/includeBytes/tests.json
Add a test for the [`fastly.includeBytes`](https://js-compute-reference-docs.edgecompute.app/interfaces/fastly.html#includebytes) sdk function, and fix an issue with `integration-tests/js-compute/build-one.sh` that was preventing it from working properly.
> test: Add an integration test for includeBytes

- Cargo.lock
- Cargo.toml
- integration-tests/js-compute/fixtures/regex/fastly.toml.in
- integration-tests/js-compute/fixtures/regex/regex.ts
- integration-tests/js-compute/fixtures/regex/tests.json
- src/main.rs
- src/regex.rs
Using the tree-sitter javascript parser, discover regular expression literals when processing javascript and emit copies of them that are immediately tested. As an example, consider this program:
```js
function handler(req) {
/foo/i.test('hello, world');
}
addEventListener('fetch', handler);
```
Before it's sent to spidermonkey, it will have the following footer appended:
```js
;{
// Precompiled regular expressions
const precompile = (r) => { r.exec('a'); r.exec('\u1000'); }
precompile(/foo/i);
}
```
Spidermonkey has two features that makes this change valid: it interns regex literals so that multiple declarations of the same literal share a single regex object under the hood; the first use of a regex will cause it to be compiled to bytecode.
I ran 100 requests against …
> feat: Precompile regex literals

- .github/workflows/main.yml
- ci/rustfmt.sh
Run `rustfmt` in CI to ensure that we're not accidentally merging unformatted PRs. You can see what a failure looks like [here](https://github.com/fastly/js-compute-runtime/runs/7313158208?check_suite_focus=true).
> Run rustfmt in CI

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/backend/backend.js
- integration-tests/js-compute/fixtures/tee/fastly.toml.in
- integration-tests/js-compute/fixtures/tee/tee.ts
- integration-tests/js-compute/fixtures/tee/tests.json
Fixes #154 
When a request's body is produced by a stream that must be read into the js-compute-runtime (such as those created with `tee` from an existing request's body) we would place the request in the same pending queue that we would use for requests whose request body handle was already closed. The effect of this was that once we entered `process_pending_requests`, we would deadlock if the only request available for processing was the one waiting on its channel to close.
The solution implemented in this PR is to only queue the request for processing when we know that its body has been closed. This change needed to happen in two places:
1. In the `fetch` implementation we need to only enqueue the request if it's not going to be streamed
2. The `then` handler constructed in …
> fix: Mark requests as pending after their body stream has closed

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
resolves https://github.com/fastly/js-compute-runtime/issues/23
> Use an enum to explicitly state what the execution phase is that the application is currently in

- Cargo.toml
- build.rs
- c-dependencies/js-compute-runtime/Makefile
Beginning to split up js-compute-builtins.cpp means that we'll benefit more from running make with a `-j` argument. This PR adds that flag to the make invocation in `build.rs`, and also ensures that the `builtins` output directory exists when building outside of the `c-dependencies/js-compute-runtime` tree.
> chore: When calling make from build.rs, pass `-j $NUM_JOBS`

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/tee/tee.ts
- integration-tests/js-compute/fixtures/tee/tests.json
- tests/wpt-harness/run-wpt.mjs
This PR does two things:
* Fixes a bug in the wpt test runner that was considering crashes to be successful runs
* Fixes a bug exposed by #156 that manifested as a crash when a `ReadableStream` didn't yield a chunk that was a byte array
> Fix the error code from the wpt runner

- c-dependencies/js-compute-runtime/error-numbers.msg
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- tests/wpt-harness/expectations/encoding/idlharness.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-error.any.js.json
Section 3.7.1 of the WebIDL (https://webidl.spec.whatwg.org/#interface-object) specifies in step 1.2 that if a WebIDL interface is called with `NewTarget` undefined (i.e. not as a constructor) then to throw a TypeError. Our implementation was throwing an Error and not a TypeError.
This commit updates our implementation to throw a TypeError with the same message format that is used within Firefox.
> Throw TypeError instead of Error if constructor called as regular function

- c-dependencies/js-compute-runtime/error-numbers.msg
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- tests/wpt-harness/expectations/compression/compression-bad-chunks.tentative.any.js.json
Step 1 of the [compress and enqueue a chunk algorithm](https://wicg.github.io/compression/#compress-and-enqueue-a-chunk) states:
> If chunk is not a [BufferSource](https://webidl.spec.whatwg.org/#BufferSource) type, then throw a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).
We currently throw an Error and not a TypeError. This pull-request updates our implementation to throw a TypeError.
> Throw a TypeError instead of an Error when value_to_buffer is handed a value which is not a buffer

- .vscode/c_cpp_properties.json
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- tests/wpt-harness/expectations/fetch/api/request/request-cache-default-conditional.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-cache-default.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-cache-force-cache.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-cache-no-cache.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-cache-no-store.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-cache-reload.any.js.json
Currently there is no way to retrieve the reason-phrase (status text) for the host-provided response. Until such a way exists, we can use the definition mapping from IANA https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
Previously we were setting the statusText to `""` - with this change, the statusText will be a standard constant from IANA if one exists and if not, it will then be `""`.
> Set the host-provided response statusText based upon the provided status code

- tests/wpt-harness/run-wpt.sh
Add the `tests/wpt-harness/run-wpt.sh` script to wrap up a common pattern for running those tests locally.
> Add a script to simplify running the wpt tests locally

- .gitmodules
- integration-tests/js-compute/fixtures/random/fastly.toml.in
- integration-tests/js-compute/fixtures/random/random.js
- integration-tests/js-compute/fixtures/random/tests.json
- tests/wpt-harness/expectations/fetch/api/basic/request-upload.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/request-upload.h2.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-cache-reload.any.js.json
This changes which commit sha we pull from to one which ensures spidermonkey uses arc4random when compiled to wasi 
By using arc4random, the prng is seeded correctly and will no longer have the first two generated numbers be similar
> Update to version of spidermoney-wasi-embedding which uses arc4random to seed the prng

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
These functions are used within the built-in classes that we plan to split out into their own files
> Prepare js-compute-builtins for being split apart

- c-dependencies/js-compute-runtime/builtin.h
- c-dependencies/js-compute-runtime/builtins/logger.cpp
- c-dependencies/js-compute-runtime/builtins/logger.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
We can use a template class with static methods instead of cpp for `CLASS_BOILERPLATE_INIT`. Defining the boilerplate this way gives us a bit better control over the names introduce by that macro.
To demonstrate how it's used, I've ported over the `Logger` class.
> Add a template to avoid the cpp for initializing js classes

- .github/workflows/release-please.yml
I'm not sure how to best test this, as the action will only look at commits on the `main` branch. The action isn't crashing and seems to be doing what we'd expect, but it won't pick up fake commits on this branch as candidates for a release.
Here's an example run on this branch: https://github.com/fastly/js-compute-runtime/runs/7566736857?check_suite_focus=true
> Enable release-please

- src/main.rs
Having different default values causes confusion and makes using the two projects together less smooth than it could be.
By aligning the default values, js projects can change their npm build script from:
`js-compute-runtime bin/index.js bin/main.wasm` to `js-compute-runtime`
> default the created wasm file to be bin/main.wasm to algin with the default configuration of the fastly cli

- .github/workflows/dependencies.yml
- .github/workflows/main.yml
- sdk/js-compute/index.d.ts
- sdk/js-compute/index.test-d.ts
- sdk/js-compute/package-lock.json
- sdk/js-compute/package.json
Resolves https://github.com/fastly/js-compute-runtime/issues/184
I've added types for:
- `onfetch`
- `fastly.baseURL`
- `fastly.defaultBackend`
- `CompressionStream`
- `DecompressionStream`
- `console.debug`
I've removed the types for `console.trace` as the method no longer exists.
I've also updated the types to the latest versions from https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts and commented out all the parts that we have not yet implemented such as `Response.redirect()` etc
> update our published types and add tests for the types

- c-dependencies/js-compute-runtime/error-numbers.msg
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/btoa/bin/index.js
- integration-tests/js-compute/fixtures/btoa/fastly.toml.in
- integration-tests/js-compute/fixtures/btoa/tests.json
- sdk/js-compute/index.d.ts
- sdk/js-compute/index.test-d.ts
- tests/wpt-harness/expectations/html/webappapis/atob/base64.any.js.json
- tests/wpt-harness/tests.json
`atob` and `btoa` are global base64 utility methods which are useful to have included in the runtime as projects such as PlnaetScale's Serverless Driver for JavaScript make use of these methods and a native implementation should be more performant than a JavaScript implementation (a polyfill)
Note: I haven't figured out how to raise an exception with a custom error class, which is required for full adherence with the specification (and to make all the web-platform-tests pass) as the function should throw InvalidCharacterError instances but we throw Error instances instead.
https://html.spec.whatwg.org/multipage/webappapis.html#atob
> feat: add btoa and atob native implementations

- .gitignore
- sdk/js-compute/package-lock.json
- sdk/js-compute/package.json
previously this was in the compute-sdk-as-js repo and was a rust c@e application. I've moved the responsibility over into this repository and hooked it into the publishing of the @fastly/js-compute package so that they always stay in sync. I also changed from using a rust c@e app to a js c@e app for the site as that seems like a nice way for us to use our own software :-)
> move the building and publishing of the js-compute documentation site into this repository

- sdk/js-compute/index.d.ts
- sdk/js-compute/index.test-d.ts
This fixes an issue in how we make our typescript types visible.
An excellent write-up of the situation can be found in this issue: https://github.com/fastly/js-compute-runtime/issues/251
> fix:  declare ambient types for the fastly/js-compute npm package

- c-dependencies/js-compute-runtime/builtins/config-store.cpp
- c-dependencies/js-compute-runtime/builtins/config-store.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/xqd.h
- integration-tests/js-compute/fixtures/config-store/bin/index.js
- integration-tests/js-compute/fixtures/config-store/fastly.toml.in
- integration-tests/js-compute/fixtures/config-store/tests.json
- sdk/js-compute/index.d.ts
- sdk/js-compute/index.test-d.ts
ConfigStore will eventually be the new name for Dictionary, but for now we will keep the Dictionary class around to allow customers to be able to slowly migrate to the new class.
> feat: Add ConfigStore class

- .github/workflows/dependencies.yml
previously we had have to relax the allow-licenses field due to a development dependency having a license which was not in the allow-list.
The newer version of dependency-review-action now has the option to specify which 'scope' to check the licenses for. I've set the scope to be 'runtime', which means it will no longer check the development dependency licenses.
In a future commit we can revert the allow-licenses field back to it's original, stricter list.
> only enforce licenses for runtime dependencies and not development dependencies

- sdk/js-compute/CHANGELOG.md
The reason we disable it by default is because Dynamic Backends open up the potential for a data exfiltration attack to be possible, which is an attack vector not previously possible on a Fastly Service.
> Add note about Dynamic Backends being disabled for Fastly Services by default

- c-dependencies/js-compute-runtime/builtins/backend.cpp
- integration-tests/js-compute/fixtures/dynamic-backend/bin/index.js
we already use inet_pton in geo_ip.cpp for get_geo_info
Source for inet_pton: https://github.com/WebAssembly/wasi-libc/blob/659ff414560721b1660a19685110e484a081c3d4/libc-top-half/musl/src/network/inet_pton.c#L15
> refactor: replace custom ip validation with inet_pton

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/picosha2.h
- integration-tests/js-compute/fixtures/request-cache-key/bin/index.js
- integration-tests/js-compute/fixtures/request-cache-key/fastly.toml.in
- integration-tests/js-compute/fixtures/request-cache-key/tests.json
- sdk/js-compute/index.d.ts
This method is used to set the cache key that will be used when attempting to satisfy this request from a cached response.
It is the equivalent of the VCL property `req.hash`.
The rust sdk version of [this method](https://docs.rs/fastly/latest/src/fastly/experimental.rs.html#183-195)
The header name is from xqd-headers
This [thread](https://fastly.slack.com/archives/CP8H97EDQ/p1664298940822429?thread_ts=1664296201.814199&cid=CP8H97EDQ) is where I learnt that this is the correct approach to take
> feat: implement Request.prototype.setCacheKey

- c-dependencies/js-compute-runtime/builtins/backend.cpp
- c-dependencies/js-compute-runtime/builtins/config-store.cpp
- c-dependencies/js-compute-runtime/builtins/dictionary.cpp
- c-dependencies/js-compute-runtime/builtins/object-store.cpp
- c-dependencies/js-compute-runtime/geo_ip.cpp
- c-dependencies/js-compute-runtime/host_call.cpp
- c-dependencies/js-compute-runtime/host_call.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
This should make it simpler to understand what each return code stands for within the codebase
> Add FastlyStatus enum and update all hostcall definitions to return FastlyStatus

- integration-tests/js-compute/fixtures/geoip/bin/index.js
- integration-tests/js-compute/fixtures/geoip/fastly.toml.in
- integration-tests/js-compute/fixtures/geoip/tests.json
We previously only tested what happens when the function is given a single valid ipv4 address
This adds tests for:
- The functions descriptors
- The functions parameter length
- Calling the function as a constructor
- Calling the function with no parameters
- Confirming the function calls ToString on the parameter
- Calling the function with an empty string
- Calling with a valid ipv4 address
- Calling with a valid compressed ipv6 address
- Calling with a valid shortened ipv6 address
- Calling with a valid expanded ipv6 address
- ~Calling with a valid dual ipv4/v6 address~ -- This test found a bug in ipll which needs to be fixed first
- Calling as an unbound function
> Add more tests for fastly.getGeolocationForIpAddress

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
- integration-tests/js-compute/fixtures/error/bin/index.js
- integration-tests/js-compute/fixtures/error/fastly.toml.in
- integration-tests/js-compute/fixtures/error/tests.json
Currently the below program will return a 200 OK, which is likely not what the user is expecting:
```js
addEventListener("fetch", event => {
throw new Error('uh oh');
});
```
This pull-request makes the above program return a 500 Internal Server Error instead
> fix: respond with 500 Internal Server Error when an unhandled error has occured and no response has already been sent to the client

- .github/workflows/main.yml
- integration-tests/js-compute/fixtures/extend-from-builtins/fastly.toml.in
- integration-tests/js-compute/fixtures/object-store/fastly.toml.in
- integration-tests/js-compute/fixtures/object-store/tests.json
This is currently blocked on landing a bugfix for viceroy's validation rules for object-store keys -- https://github.com/fastly/Viceroy/pull/170
> run object-store tests via viceroy

- .github/workflows/release-please.yml
Currently the publishing of both these things is done within the compute-sdk-as-js repository. as we are moving away from that repository and into this public one, I have added automation for publishing to npm when the @fastly/js-compute package has been updated by our release-please pull-requests.
The process is not yet fully automated for making a release as we still need to commit the built binaries into @fastly/js-compute - once we complete the work to avoid commiting the binaries then this can become fully automated!
> Automatically publish the npm package and associated documentation website

- .github/workflows/main.yml
- .vscode/settings.json
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
- c-dependencies/js-compute-runtime/xqd.h
- integration-tests/js-compute/fixtures/timers/bin/index.js
- integration-tests/js-compute/fixtures/timers/fastly.toml.in
- integration-tests/js-compute/fixtures/timers/tests.json
- tests/wpt-harness/expectations/html/webappapis/timers/clearinterval-from-callback.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/cleartimeout-clearinterval.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/missing-timeout-setinterval.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/negative-setinterval.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/negative-settimeout.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/type-long-setinterval.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/type-long-settimeout.any.js.json
- tests/wpt-harness/post-harness.js
- tests/wpt-harness/tests.json
Using the new fastly_async_io module we can implement JS timers 🥳 
This pull-request implements setTimeout, setInterval, clearTimeout, and clearInterval and adds some interface and basic tests for them. There are also tests in the web-platform-tests that exercise the functions fully, which is why I only needed to write some basic tests.
Currently Viceroy does not have a host implementation for fastly_async_io so for now our tests can only run in production.
Closes #63
> feature: implement setTimeout, setInterval, clearTimeout, and clearInterval

- src/containsSyntaxErrors.js
This PR is a fix for the case when, like in my environment, `process.execPath` returns a path that includes a space:
```
/Users/komuro/Library/Application Support/fnm/node-versions/v18.6.0/installation/bin/node
```
The `containsSyntaxErrors` function calls `child_process.spawnSync()` with this string, which gives this error:
```
/bin/sh: /Users/komuro/Library/Application: No such file or directory
```
Since `child_process.spawnSync()` is called with `shell: true`, the first parameter can and should be passed as a quoted string to avoid problems with spaces.
I wasn't able to figure out how to write a test in the integration framework that would test for this case... if this needs an integration test I will need help.
> fix: Allow process.execPath to contain whitespace

- index.d.ts
- index.test-d.ts
This PR adds types for setTimeout/clearTimeout/setInterval/clearInterval. If you're using TypeScript, then declarations for these are needed to use them.
```typescript
/// <reference types="@fastly/js-compute" />
addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));
async function handleRequest(event: FetchEvent) {
await new Promise<void>(resolve => {
setTimeout(() => { resolve(); }, 1000);
});
return new Response("OK", { status: 200 });
}
```
```
ERROR in /Users/komuro/Developer/learning/c-at-e/ts/src/index.ts
./src/index.ts 8:4-14
[tsl] ERROR in /Users/komuro/Developer/learning/c-at-e/ts/src/index.ts(8,5)
TS2304: Cannot find name 'setTimeout'.
```
> fix: Add types for setTimeout/etc

- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Previously, if an error occurred during streaming, we would close the body, which is the host interprets as a successful response and so the response body would contain `0\r\n\r\n` at the end which indicates the  successful termination of a chunk-encoded response however, this was not meant to be a successful response as an error occurred.
This commit changes the behavior to not close the response body when an error occurs, which in turn means `0\r\n\r\n` is not added to the end of the response and the downstream client will know that the response was not successfully terminated.
We can't yet confirm this behavior with a test as neither viceroy nor c@e have the latest version of the ABI.
I've confirmed this is working with a manual test using a local version of Viceroy which has the new …
> fix: When streaming a response to the host, do not close the response body if an error occurs

- DEVELOPMENT.md
Simple typo fix in the `DEVELOPMENT.md` docs for "dependencies". Sorry if annoying, feel free to close!
> docs: fix deps typo in DEVELOPMENT.md

- package.json
- tests/wpt-harness/run-wpt.sh
Build the runtime using `npm run build` in the root instead of running make in `c-dependencies/js-compute-runtime`.
> chore: Fix the tests/wpt-harness/run-wpt.sh script

- .github/workflows/main.yml
- DEVELOPMENT.md
- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/builtins/backend.cpp
- c-dependencies/js-compute-runtime/builtins/url.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
- c-dependencies/js-compute-runtime/wizer.h
- c-dependencies/rust-toolchain.toml
- rust-toolchain.toml
- tests/wpt-harness/expectations/html/webappapis/structured-clone/structured-clone.any.js.json
Bump our spidermonkey dependency to the version included with firefox 107.
This shouldn't merge before https://github.com/fastly/spidermonkey-wasi-embedding/pull/6, but it's ready for review in the meantime.
> Bump spidermonkey

- .github/workflows/main.yml
- DEVELOPMENT.md
- package.json
- src/compileApplicationToWasm.js
- yarn.lock
As wasi-sdk-16 uses a version of llvm that produces uses of `memory.copy`, we need to enable the wizer flag for handling bulk memory.
This PR required bumping our wizer dependency, to get a bug fix for handling data sections https://github.com/bytecodealliance/wizer/pull/61.
> Update to wasi-sdk-16

- c-dependencies/js-compute-runtime/Makefile
* Add a variable for the path to wasi-sdk
* Use the `--sysroot` flag when compiling with wasi-sdk
* Reorganize long variable definitions into uses of `+=`
* Add a comment explaining `-DMOZ_JS_STREAMS`
> chore: Makefile improvements

- .github/workflows/main.yml
- .github/workflows/release-please.yml
- DEVELOPMENT.md
- c-dependencies/js-compute-runtime/Makefile
- Upgrade to wasi-sdk-17
- Remove unused linker flags
> chore: Upgrade to wasi-sdk-17

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/scripts/wasm-opt
Clang now runs `wasm-opt` automatically if it's present in the path when linking wasm artifacts. For debug builds on osx this produces a bus error, it's also not clear that we want `wasm-opt -O2` applied to our debug artifacts.
This PR introduces a script named `wasm-opt` that immediately exits successfully, and adds it to the PATH when linking the runtime. This prevents clang from running the real `wasm-opt`, and gives us more control over what optimizations are enabled when we do choose to run it.
> Wrap wasm-opt to prevent clang from running it in debug builds

- README.md
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- reference-docs/v0.5.10/index.html
- reference-docs/v0.5.11/index.html
- reference-docs/v0.5.12/index.html
- reference-docs/v0.5.13/index.html
- reference-docs/v0.5.14/index.html
- reference-docs/v0.5.15/index.html
- reference-docs/v0.5.9/index.html
- reference-docs/v0.7.0/index.html
- reference-docs/v1.0.0/index.html
This change interCaps JavaScript properly. It changes a few references from "Javascript" to "JavaScript".
> JavaScript, not Javascript

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/getuid.patch
Add a target in our makefile for downloading and building OpenSSL. The Makefile will fetch and build OpenSSL for c++ dependencies, and then add it to the include and linker paths.
We don't currently cache the download of openssl in CI, this would probably be worth doing.
> chore: Build openssl

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/.gitignore
- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/commands.mk
Refactor the makefile to better document the build system, and provide better separation for release and debug builds. Also:
* prettier output
* more precise clean commands
* lots of comments
I've also removed the `compiler_flags` and `Makefile` dependencies, as cleaning and rebuilding should generally be pretty quick.
> chore: Rework the makefile

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/request-clone/bin/index.js
- integration-tests/js-compute/fixtures/request-clone/fastly.toml.in
- integration-tests/js-compute/fixtures/request-clone/tests.json
- tests/wpt-harness/expectations/fetch/api/request/request-structure.any.js.json
This commit adds a native implementation for Request.prototype.clone - The clone() method creates a copy of the current Request object.
> feat: implement Request.prototype.clone

- c-dependencies/js-compute-runtime/allocator.cpp
- c-dependencies/js-compute-runtime/allocator.h
- c-dependencies/js-compute-runtime/xqd-world/xqd_world_adapter.cpp
- c-dependencies/js-compute-runtime/xqd-world/xqd_world_adapter.h
Introduce a strong symbol for `cabi_realloc` to ensure that we're always calling `JS_realloc`, and some convenience functions for helping to identify when memory is managed by wit-bindgen-generated code.
> Introduce allocation wrappers around spidermonkeys allocator api

- c-dependencies/js-compute-runtime/builtins/object-store.cpp
- c-dependencies/js-compute-runtime/host_api.cpp
- c-dependencies/js-compute-runtime/host_api.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
Start implementing an abstraction layer over the host call interface, so that we can take advantage of smart pointers and other c++ convenience features.
> chore: C++ interface to host calls

- c-dependencies/js-compute-runtime/builtins/cache-override.cpp
- c-dependencies/js-compute-runtime/builtins/cache-override.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/xqd-world/xqd_world_adapter.cpp
This provides the proper flag-based implementation of `convert_tag`, whereas the previous function which was behind https://github.com/fastly/js-compute-runtime/pull/386 was implemented as if it were an enum object instead.
This avoids assuming flag binary alignment between xqd and the component model.
> component: reinclude conversion function to avoid world-based binary assumptions

- .github/workflows/main.yml
- .github/workflows/release-please.yml
- DEVELOPMENT.md
Bump the version of wasi-sdk we build with to version 19.
> chore: Bump wasi-sdk to version 19

- c-dependencies/js-compute-runtime/xqd-world/xqd_world_adapter.cpp
- integration-tests/js-compute/fixtures/multiple-set-cookie/bin/index.js
- integration-tests/js-compute/fixtures/multiple-set-cookie/fastly.toml.in
- integration-tests/js-compute/fixtures/multiple-set-cookie/tests.json
Currently a C@E application retrieving multiple headers with the same name will crash due to a wasm out-of-bounds access.
This is due to the amount of memory we allocate to retrieving header values from the host. Looking into our memory allocation, it looks like we forgot to multiply the amount of headers by the size of a `xqd_world_string_t`. I've updated our allocation to account for the size of `xqd_world_string_t` and written a test to confirm this stop the application crashing.
We don't need to worry about headers being greater than this size, as it is the max size supported by c@e/viceroy 👍
> fix: allow lots of the same header name to exist within a request or response

- c-dependencies/js-compute-runtime/xqd-world/xqd_world_adapter.cpp
Rework `xqd_fastly_http_req_header_names_get` to avoid any need to explicitly free the memory that it manages.
> Refactor header_names_get to avoid explicitly freeing memory

- c-dependencies/js-compute-runtime/host_call.h
We should not be sending out these error codes as they are not something we guarantee will stay the same and we will possibly move to a different way of modelling internal error in the future
> fix: Remove error codes from external error messaging

- c-dependencies/js-compute-runtime/builtins/compression-stream.cpp
- c-dependencies/js-compute-runtime/builtins/decompression-stream.cpp
- c-dependencies/js-compute-runtime/builtins/subtle-crypto.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
Refactor `value_to_buffer` to return a `std::optional<std::span<uint8_t>>` instead of a pair of a pointer and length argument through an out argument. This avoids the need to manage an out argument, and gates all outputs on success.
We could alternately return a `std::span<uint8_t>` with a null data pointer, but wrapping this in an optional felt like the easiest way to avoid misinterpreting the result.
> chore: Return an optional span from `value_to_buffer`

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/error-numbers.msg
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- integration-tests/js-compute/fixtures/missing-backend/bin/index.js
- integration-tests/js-compute/fixtures/missing-backend/fastly.toml.in
- integration-tests/js-compute/fixtures/missing-backend/tests.json
previously we would return the generic message: "Generic error value. This means that some unexpected error occurred during a hostcall."
Now we will return a TypeError with the message format `Requested backend named '{0}' does not exist` where `{0}` is the name of the backend that was configured for the request.
> fix: add custom error message when making a request to a backend which does not exist

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/builtin.h
Fixes the build by doing the following:
* Bump viceroy to version 0.3.5
* Bump spidermonkey to version 110
The spidermonkey build required a small update to the builtins, as the signature for `JS_InitClass` changed.
> fix: Bump to spidermonkey 110, and viceroy 0.3.5

- types/globals.d.ts
1.2.0 added Request.prototype.clone. Seems the TypeScript definitions weren't updated for this, so this PR adds that.
> docs: Add types def for clone

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/builtin-error-numbers.msg
- c-dependencies/js-compute-runtime/builtin.cpp
- c-dependencies/js-compute-runtime/builtin.h
- c-dependencies/js-compute-runtime/builtins/backend.cpp
- c-dependencies/js-compute-runtime/builtins/backend.h
- c-dependencies/js-compute-runtime/builtins/cache-override.h
- c-dependencies/js-compute-runtime/builtins/compression-stream.h
- c-dependencies/js-compute-runtime/builtins/config-store.h
- c-dependencies/js-compute-runtime/builtins/crypto.h
- c-dependencies/js-compute-runtime/builtins/decompression-stream.h
- c-dependencies/js-compute-runtime/builtins/dictionary.h
- c-dependencies/js-compute-runtime/builtins/env.h
- c-dependencies/js-compute-runtime/builtins/fastly.h
- c-dependencies/js-compute-runtime/builtins/logger.h
- c-dependencies/js-compute-runtime/builtins/native-stream-sink.h
- c-dependencies/js-compute-runtime/builtins/native-stream-source.h
- c-dependencies/js-compute-runtime/builtins/object-store.h
- c-dependencies/js-compute-runtime/builtins/secret-store.h
- c-dependencies/js-compute-runtime/builtins/subtle-crypto.h
- c-dependencies/js-compute-runtime/builtins/transform-stream-default-controller.h
- c-dependencies/js-compute-runtime/builtins/transform-stream.h
- c-dependencies/js-compute-runtime/builtins/url.h
- c-dependencies/js-compute-runtime/builtins/worker-location.h
- c-dependencies/js-compute-runtime/commands.mk
- c-dependencies/js-compute-runtime/error-numbers.msg
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
This fully separates the builtins build by including the `encode` function and also including a custom `GetErrorMessageBuiltin` with separate builtin error message codes so that the error message pipeline for the builtins is completely separated from the Fastly-specific code.
Structuring feedback very welcome, but I can confirm this works for building the console against ComponentizeJS.
> fix: modular builtin separation

- integration-tests/cli/component.test.js
- package.json
- src/compileApplicationToWasm.js
- yarn.lock
This includes the fix from https://github.com/bytecodealliance/wizer/pull/71, as well as moving over the bytecodealliance org version on npm.
> deps: upgrade to @bytecodeallianace/wizer@1.6.1-beta.4

- .github/actions/e2e/action.yml
- .github/workflows/main.yml
- .github/workflows/release-please.yml
- integration-tests/js-compute/fixtures/object-store/setup.js
- Bump the fastly cli
- Silence noisy fastly cli command in the object-store test
> chore: Bump the fastly-cli version in CI

- src/precompile.js
Resolves https://github.com/fastly/js-compute-runtime/issues/446.
While the root cause fix is https://github.com/jviereck/regjsparser/issues/130, we shouldn't expose parser bugs, and rather fall through to the engine, as well as in the case of an invalid regex more generally.
> fix: handle fallthrough of regex parser bugs

- c-dependencies/js-compute-runtime/Makefile
- c-dependencies/js-compute-runtime/builtins/headers.cpp
- c-dependencies/js-compute-runtime/host_interface/host_api.cpp
- c-dependencies/js-compute-runtime/host_interface/host_api.h
Add `HttpReq` and `HttpResp` to the host_api abstraction, and add support for headers. Additionally, migrate the `Headers` implementation to use this new interface.
> Start adding Request and Response types to host_api

- c-dependencies/js-compute-runtime/builtins/request-response.cpp
- c-dependencies/js-compute-runtime/builtins/request-response.h
- c-dependencies/js-compute-runtime/host_interface/host_api.cpp
- c-dependencies/js-compute-runtime/host_interface/host_api.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
Cleanup the host_api interface a bit, by standardizing more on `HostString`.
> Remove HttpBodyChunk in favor of HostString

- c-dependencies/js-compute-runtime/builtin.h
- c-dependencies/js-compute-runtime/builtins/crypto-key.cpp
- c-dependencies/js-compute-runtime/builtins/crypto-key.h
Spec: https://w3c.github.io/webcrypto/#cryptokey-interface
This implements the basic interface of a CryptoKey:
- Exposing a public constructor which throws an JS Error when called
- Defining the interface/instance members (https://w3c.github.io/webcrypto/#cryptokey-interface-members)
- Defining all the internal slots that are required for the interface
This class cannot currently be used by a JS application due to the fact CryptoKey can only be constructed by the SubtleCrypto methods `generateKey` and `importKey`, which are not yet implemented. Future pull-requests will implement those methods, and also include tests to confirm the behavior of the CryptoKey interface
> feat: Implement JS CryptoKey Interface

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/Makefile
- js-compute-runtime-cli.js
- src/addSdkMetadataField.js
This adds the SDK field "@fastly/js-compute" with it's value being the version of `@fastly/js-compute` used.
We add the metadata field to the runtime wasm files `js-compute-runtime.wasm` and `js-compute-runtime-component.wasm` and to the wasm files generated by the `js-compute-runtime` command.
The metadata fields on the wasm files generated by the `js-compute-runtime` command are useful for helping debug wasm applications, as we will be able to see which version of the runtime is being used.
This is the metadata which is now attached to our wasm files:
```
module:
language:
C_plus_plus_14
C99
Rust
processed-by:
clang: 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)
rustc: 1.67.1 (d5a82bbd2 2023-02-07)
sdk:
@fastly/js-compute: 1.5.2
```
> chore: Add SDK metadata field to generated wasm files

- .github/workflows/main.yml
- c-dependencies/js-compute-runtime/rust-url/src/lib.rs
- integration-tests/js-compute/fixtures/urlsearchparams/bin/index.js
- integration-tests/js-compute/fixtures/urlsearchparams/fastly.toml.in
- integration-tests/js-compute/fixtures/urlsearchparams/tests.json
- tests/wpt-harness/expectations/url/urlsearchparams-delete.any.js.json
- tests/wpt-harness/expectations/url/urlsearchparams-sort.any.js.json
fixes https://github.com/fastly/js-compute-runtime/issues/484
> fix: When converting a URL to a string, do not add a `?` if there are no query string parameters

- package.json
- src/precompile.js
- yarn.lock
This replaces the use of tree-sitter with Acorn and Magic String, and should enable Node.js 20 support more easily.
> feat: replace tree-sitter with acorn + magic string

- c-dependencies/js-compute-runtime/builtins/fastly.cpp
- c-dependencies/js-compute-runtime/builtins/fastly.h
- c-dependencies/js-compute-runtime/js-compute-builtins.cpp
- c-dependencies/js-compute-runtime/js-compute-builtins.h
- c-dependencies/js-compute-runtime/js-compute-runtime.cpp
- integration-tests/cli/help.test.js
- integration-tests/js-compute/fixtures/fastly/bin/index.js
- integration-tests/js-compute/fixtures/fastly/fastly.toml.in
- integration-tests/js-compute/fixtures/fastly/tests.json
- js-compute-runtime-cli.js
- src/compileApplicationToWasm.js
- src/parseInputs.js
- src/printHelp.js
This function accepts no arguments and returns the number of Microseconds since the epoch, midnight, January 1, 1970 UTC.
This function is very useful to have for running performance tests within JavaScript applications.
Still TODO:
> feat: Add high-resolution timing function "fastly.now()" behind feature flag "--enable-experimental-high-resolution-time-methods"

- .github/workflows/main.yml
- package.json
Thanks to the work done by @guybedford  in https://github.com/fastly/js-compute-runtime/pull/488
> fix: Mark NodeJS 19 and 20 as supported

- .github/workflows/main.yml
- .gitignore
- package.json
- yarn.lock
A few times now we have broken updates the Developer Portal Changelog page for the JS SDK due to our changelog.md being non-conformant. This PR adds a CI step which will fail if we are non-conformant, thereby ensuring we always are conformant 😄
> chore: Make sure our changelog.md file conforms with the format for Changelog ingestion for the Developer Portal

- src/precompile.js
This PR fixes the following error thrown by the compiler when `import`-ing certain libraries:
```
> build
> js-compute-runtime bin/index.js bin/main.wasm
file:///Users/komuro/Developer/my-app/node_modules/@fastly/js-compute/src/precompile.js:37
transpiledPattern = pattern;
^
ReferenceError: pattern is not defined
at Literal (file:///Users/komuro/Developer/my-app/node_modules/@fastly/js-compute/src/precompile.js:37:9)
at c (file:///Users/komuro/Developer/my-app/node_modules/acorn-walk/dist/walk.mjs:24:18)
at Object.skipThrough (file:///Users/komuro/Developer/my-app/node_modules/acorn-walk/dist/walk.mjs:180:37)
at c (file:///Users/komuro/Developer/my-app/node_modules/acorn-walk/dist/walk.mjs:23:22)
at base.ArrayExpression (file:///Users/komuro/Developer/my-app/node_modules/acorn-walk/dist/wa …
```
> fix: Fix for `ReferenceError: pattern is not defined`

- types/globals.d.ts
This PR adds TypeScript declarations for `Response.redirect()` and `Response.json()`.
I wasn't able to figure out where to add them in `globals.test-d.ts` however, so @JakeChampion  or @guybedford please advise on where to put them (or add them for me thanks).
> fix: Add TypeScript definitions for Response.redirect() and Response.json()

- .github/workflows/dependencies.yml
tinyvec and tinvec_macros use this combination and the workflow required we specify the exact combination, even if we have specified MIT and Apache 2.0 already...
This unblocks https://github.com/fastly/js-compute-runtime/pull/514
> chore: allow the license combo Zlib OR Apache-2.0 OR MIT

- runtime/rust-toolchain.toml
They drifted apart because spidermonkey-wasi-embedding does not have a rust-toolchain file, which meant the pre-built spidermonkey-wasi would no longer link due to having conflicting/duplicate symbols.
This patch updates our rust-toolchain to match the version used in spidermonkey-wasi-embedding - I have also added the same file to the spidermonkey-wasi-embedding project ot ensure they are on the same version.
Fixes https://github.com/fastly/js-compute-runtime/issues/520
> chore: use same rust version as https://github.com/fastly/spidermonkey-wasi-embedding/

- runtime/js-compute-runtime/Makefile
The rule that produced `compile_commands.json` was producing paths that didn't point to the actual files. Fix this by using the absolute paths in `compile_commands.json` instead.
> chore: Fix compile_commands.json

- runtime/js-compute-runtime/builtins/fastly.cpp
- runtime/js-compute-runtime/builtins/fetch-event.cpp
- runtime/js-compute-runtime/builtins/fetch-event.h
- runtime/js-compute-runtime/builtins/object-store.cpp
- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/builtins/request-response.h
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
- runtime/js-compute-runtime/js-compute-runtime.cpp
Migrate the request/response API away from using the fastly world types directly, replacing them with the corresponding host_api types.
> Migrate more of request/response to host_api

- SECURITY.md
The SECURITY.md file seems to have been copied from other repo but kept a reference to its name.
This MR updates it to avoid confusion.
I know it is a small contribution, but it is something =)
> Fix pasted text from other repository

- CHANGELOG.md
- DEVELOPMENT.md
- documentation/docs/migration-guide/index.mdx
- documentation/versioned_docs/version-2.0.0/migration-guide/index.mdx
- js-compute-runtime-cli.js
Hello!
Sorry to bother again with small things :zany_face: 
Spotted a few typos and also I've ran into a problem running `sh download-engine.sh` instead of `bash download-engine.sh` getting the error `Illegal option -o pipefail`, I believe due to `#!/usr/bin/env bash` resolving to `sh` on Ubuntu 22.04 and not recognizing -o pipefail as a legal option
> Fix typos and minor doc changes

- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/builtins/request-response.h
- runtime/js-compute-runtime/fastly-world/fastly_world_adapter.cpp
- runtime/js-compute-runtime/fastly.wit
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
Introduce an `AsyncHandle` type to the host api, and refactor the event loop to use them instead.
I reworked the interface to the underlying `fastly_async_io_select` host call, so that it's now a bit more clear when the timeout has expired. I've also added comments to `process_pending_async_tasks` to better explain the interactions between the two action queues.
> Abstract over async handles

- runtime/js-compute-runtime/builtins/fetch-event.cpp
- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
Remove direct uses of the `fastly_` functions from the `request-response` and `fetch-request` builtin modules.
> Fully migrate request-response and fetch-request to the host_api

- runtime/js-compute-runtime/builtins/backend.cpp
- runtime/js-compute-runtime/builtins/client-info.cpp
- runtime/js-compute-runtime/builtins/config-store.cpp
- runtime/js-compute-runtime/builtins/config-store.h
- runtime/js-compute-runtime/builtins/dictionary.cpp
- runtime/js-compute-runtime/builtins/dictionary.h
- runtime/js-compute-runtime/builtins/kv-store.cpp
- runtime/js-compute-runtime/builtins/kv-store.h
- runtime/js-compute-runtime/builtins/logger.cpp
- runtime/js-compute-runtime/builtins/secret-store.cpp
- runtime/js-compute-runtime/builtins/secret-store.h
- runtime/js-compute-runtime/core/geo_ip.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
Migrate all remaining direct uses of the `fastly_` functions to the host_api. This further reduces the number places that we're explicitly managing memory lifetimes, and improves the ergonomics of working with strings at the host call boundary.
> Finish migrating to the host_api

- runtime/js-compute-runtime/builtins/crypto-algorithm.cpp
- runtime/js-compute-runtime/builtins/crypto-key.cpp
- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/builtins/shared/text-encoder.cpp
- runtime/js-compute-runtime/js-compute-builtins.cpp
Remove all but three direct uses of `JS_free`, replacing them with either `mozilla::UniquePtr`, or `std::vector`. The resulting pattern is that direct calls to `JS_free` are no longer needed, and functions that take ownership of memory now need to use calls to `.release()` on the unique pointers.
I also noticed that I missed a call-site to `fastly_http_req_uri_get` when converting over to the host_api, so I've updated that as well.
> Remove more direct uses of `free`, replacing them with unique ptrs

- src/compileApplicationToWasm.js
pretty sure that `${input}` was meant to be in a ``` `` ``` string
> cli: show file name when failing to open input

- .github/workflows/main.yml
- integration-tests/js-compute/fixtures/transform-stream/bin/index.js
- integration-tests/js-compute/fixtures/transform-stream/fastly.toml.in
- integration-tests/js-compute/fixtures/transform-stream/tests.json
- runtime/js-compute-runtime/builtins/transform-stream.cpp
- runtime/js-compute-runtime/builtins/transform-stream.h
We have a performance optimisation for when the receiver is a native source, whereby we append the entire source body to the destination using a single native hostcall, this greatly improves the performance (https://barstool.engineering/a-real-world-comparison-between-cloudflare-workers-and-fastly-compute-edge/)
This optimisation however, should only be applied when the TransformStream is being used in this particular, having not supplied a transformer to the TransformStream constuctor, i.e. an IdentityStream. If we apply the optimisation when a transformer is supplied, the transformer would never get called, which is not correct behavior.
We want to apply the optimisation in this scenario:
```ts
function combineStreams(streams: ReadableStream[]): ReadableStream {
const stream = new …
```
> fix: only apply our pipeTo/pipeThrough optimisations to TransformStreams who have no transformers (IdentityStreams).

- types/globals.d.ts
These were added in version 1.9.0 but I forgot to update the types at the same time -- https://github.com/fastly/js-compute-runtime/blob/main/CHANGELOG.md#190-2023-04-15
> fix: update types for subtlecrypto to show we support a subset of importKey/sign/verify

- CHANGELOG.md
- documentation/docs/fastly:cache/SimpleCache/SimpleCache.mdx
- documentation/docs/fastly:cache/SimpleCache/getOrSet.mdx
- documentation/docs/fastly:cache/SimpleCache/purge.mdx
- documentation/docs/fastly:cache/SimpleCache/set.mdx
This change fixes the SimpleCache example to work correctly, by using Request's `.url` property.
> Fix SimpleCache example

- runtime/js-compute-runtime/builtin.h
- runtime/js-compute-runtime/builtins/backend.cpp
- runtime/js-compute-runtime/builtins/cache-override.cpp
- runtime/js-compute-runtime/builtins/cache-simple.cpp
- runtime/js-compute-runtime/builtins/cache-simple.h
- runtime/js-compute-runtime/builtins/config-store.cpp
- runtime/js-compute-runtime/builtins/dictionary.cpp
- runtime/js-compute-runtime/builtins/kv-store.cpp
- runtime/js-compute-runtime/builtins/secret-store.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.h
Instead of re-exporting the api defined by `fastly_world.h` through `host_api.h`, introduce type synonyms for handle types and enforce through static asserts that the representation is the same. Consumers of `host_api.h` that require access to `fastly_world.h` now access it directly, reducing the number of files that are affected directly by changes to `fastly.wit`, and making it a little more difficult to use the generated api directly.
> Remove the fastly_world.h include from host_api.h

- .github/workflows/main.yml
- .gitignore
- package.json
- runtime/js-compute-runtime/Makefile
- src/component.js
Instead of using `componentEmbed` with `fastly.wit` when building a component, compile the type object into the component runtime directly. This removes the need to bundle `fastly.wit` with the js-compute-runtime package.
> chore: Compile the type information from wit-bindgen into components directly

- integration-tests/js-compute/fixtures/request-clone/bin/index.js
- runtime/js-compute-runtime/builtins/request-response.cpp
This resolves a spec non-compliance issue with our Request.prototype.clone implementation, previously we would create a new body if the request being cloned did not have a body, which is not what we should be doing, if the request being cloned does not have a body, then the new request should also not have a body 👍
> fix: Request.prototype.clone - Do not create a body on the new request if the request instance being cloned does not contain a body

- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/core/event_loop.cpp
- runtime/js-compute-runtime/core/event_loop.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
- runtime/js-compute-runtime/js-compute-builtins.h
- runtime/js-compute-runtime/js-compute-runtime.cpp
Move the event loop to its own file, and fix a memory leak with timer management. (We weren't deleting `Timer`s that had been allocated with `new`, so I switched to storing `std::unique_ptr<Timer>` values to ensure that they get free'd.)
> chore: Split the event loop out of js-compute-builtins.cpp

- runtime/js-compute-runtime/builtins/backend.cpp
- runtime/js-compute-runtime/builtins/cache-override.cpp
- runtime/js-compute-runtime/builtins/cache-override.h
- runtime/js-compute-runtime/builtins/crypto.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- Remove direct dependencies on fastly.h from crypto and cache-override
- Remove direct dependencies on fastly.h from backend.cpp
> chore: Remove fastly.h dependencies from crypto, cache-override, and backend

- integration-tests/js-compute/fixtures/client/bin/index.js
- integration-tests/js-compute/test-harness.js
- runtime/js-compute-runtime/builtins/client-info.cpp
- runtime/js-compute-runtime/builtins/client-info.h
Currently we will create new buffers/strings whenever any of the client getters are invoked, considering these never change for the duration of the application's lifetime, let's cache them so that we don't use up more memory than necessary. Currently you can use up all available memory just by reading `event.client.tlsClientCertificate` a couple times.
> fix: reduce memory usage by caching client getters when they are first called

- runtime/js-compute-runtime/builtins/cache-simple.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
Rework `cache-simple.cpp` to rely only on the host_api. This simplifies integration of changes to the `fastly.wit` generated api, as we'll likely only need to update `host_api.cpp` when it changes.
Additionally, I introduced an RAII type for managing transactions with cache handles that will automatically reject promises when exiting through a path that should cancel the transaction. This removed quite a lot of repetition from error handling in `cache-simple.cpp`, as we could replace much of it with just `return false`.
> chore: Remove direct uses of fastly-world symbols from the simple-cache api

- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
Add a function to `host_api::Random` that returns a `uint32_t`, allowing us to remove the direct dependency on `host_interface/fastly.h` from `js-compute-builtins.cpp`.
> chore: Remove fastly.h references from js-compute-builtins.cpp

- js-compute-runtime-cli.js
- src/component.js
- src/parseInputs.js
Allow overriding the component adapter wasm path, to simplify debugging with newer versions of the adapter.
I left out documentation for this flag, as we currently don't document the `--component` flag. I also chose to have this flag imply `--component`, as there's no reason to have one without the other.
> chore: Add a flag to allow an alternate component adapter to be specified

- runtime/js-compute-runtime/Makefile
Resolve linker errors with the shared-builtins.a target by include `core/encode.o`.
> chore: Include encode.o in shared builtins

- .github/workflows/main.yml
Node.js 19 has become unsupported, Node.js 20 is supported, let's use that 
>Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. Production applications should only use Active LTS or Maintenance LTS releases.
>https://nodejs.dev/en/about/releases/
> Use nodejs 20 instead of nodejs 19 in ci

- documentation/docs/globals/Request/Request.mdx
- documentation/docs/globals/fetch.mdx
- integration-tests/js-compute/fixtures/request-auto-decompress/bin/index.js
- integration-tests/js-compute/fixtures/request-auto-decompress/fastly.toml.in
- integration-tests/js-compute/fixtures/request-auto-decompress/tests.json
- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/builtins/request-response.h
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
- runtime/js-compute-runtime/host_interface/fastly.h
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
- types/globals.d.ts
This patch add a new `fastly` options object to the RequestInit parameter on `fetch` and the `Request` constructor. The new `fastly` options object has one field, `decompress`, if this field is falsey, then no automatic decompression is applied on the response. If this field is truthy, then automatic decompression is applied on the response.
This patch brings in support for automatically decompressing GZIP and not other compression formats.
I've added this under a field named `fastly` as that can be our extension point for other Fastly specific request/response features.
Previously we've added Fastly specific features as a root property on the RequestInit object, such as `backend`, `cacheOverride`, and `cacheKey`. In future patches we could move those to exist under `fastly` instead of …
> feat: add ability to automatically decompress gzip responses returned from `fetch`

- .github/workflows/dependencies.yml
- runtime/js-compute-runtime/rust-url/Cargo.lock
- runtime/js-compute-runtime/rust-url/Cargo.toml
- tests/wpt-harness/expectations/compression/decompression-corrupt-input.tentative.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/integrity.sub.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/request-forbidden-headers.any.js.json
- tests/wpt-harness/expectations/fetch/api/basic/request-upload.h2.any.js.json
- tests/wpt-harness/expectations/fetch/api/headers/headers-basic.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-error.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-headers.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-structure.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-cancel-stream.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-static-error.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-static-json.any.js.json
- tests/wpt-harness/expectations/html/webappapis/structured-clone/structured-clone.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/negative-setinterval.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/negative-settimeout.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/type-long-setinterval.any.js.json
- tests/wpt-harness/expectations/html/webappapis/timers/type-long-settimeout.any.js.json
- tests/wpt-harness/expectations/streams/readable-streams/bad-strategies.any.js.json
- tests/wpt-harness/expectations/url/url-constructor.any.js.json
- tests/wpt-harness/expectations/url/url-origin.any.js.json
- tests/wpt-harness/expectations/url/url-setters.any.js.json
- tests/wpt-harness/expectations/url/url-tojson.any.js.json
- tests/wpt-harness/expectations/url/urlencoded-parser.any.js.json
- tests/wpt-harness/expectations/url/urlsearchparams-delete.any.js.json
- tests/wpt-harness/expectations/url/urlsearchparams-has.any.js.json
- tests/wpt-harness/expectations/webidl/ecmascript-binding/es-exceptions/DOMException-constants.any.js.json
The wpt update brings in more tests
The url crate update passes some more of the url tests 😄
> update wpt submodule and url crate

- documentation/docs/globals/FetchEvent/FetchEvent.mdx
- test-d/globals.test-d.ts
- types/globals.d.ts
When I added these fields in v3.0.0 I forgot to also include typescript definitions and documentation for them
Resolves https://github.com/fastly/js-compute-runtime/issues/624
> fix: Add documentation and type definitions for the new event.client.* fields

- js-compute-runtime-cli.js
- runtime/js-compute-runtime/js-compute-runtime.cpp
- src/bundle.js
- src/compileApplicationToWasm.js
- src/parseInputs.js
The Portable Baseline Interpreter (PBL, pronounced "pebble") is a new execution tier developed for the SpiderMonkey JS engine. PBL fits into the tier hierarchy just above the generic interpreter ("C++ interpreter") and below the "baseline interpreter". Unlike the true "baseline interpreter", PBL does not require code generation (JIT'ing): it consists of an interpreter loop for JS opcodes in pure C++, but maintains data structures (strict JIT stack frame layout, use of IC data) as the other baseline tiers do. Crucially, PBL also allows use of ICs (inline caches) by including a generic CacheIR interpreter that can execute the dynamically-generated "IC stubs" with fastpathed behavior as it is discovered. PBL thus leverages existing engine functionality (JIT frame management, CacheIR) and …
> feat: Add option to enable PBL.

- .github/actions/e2e/action.yml
- .github/workflows/main.yml
- integration-tests/js-compute/fixtures/config-store/fastly.toml.in
- integration-tests/js-compute/fixtures/edge-dictionary/fastly.toml.in
- integration-tests/js-compute/fixtures/edge-dictionary/setup.js
- integration-tests/js-compute/fixtures/edge-dictionary/teardown.js
- integration-tests/js-compute/fixtures/secret-store/setup.js
- integration-tests/js-compute/fixtures/secret-store/teardown.js
- integration-tests/js-compute/test.js
Bump the fastly-cli version to 10.3.0, and expose it as an input to the e2e tests.
> chore: Update the fastly cli used in ci to 10.3.0

- DEVELOPMENT.md
- tests/wpt-harness/run-wpt.sh
we not longer have a download-engine script, this commit updates our documentation to reference how to compile the engine with our build-engine script
> update documentation to use build-engine

- documentation/docs/globals/Request/prototype/clone.mdx
This method was added in version 1.2.0 and never documented 🙈
> fix: Add documentation for Request.prototype.clone()

- documentation/docs/fastly:cache/SimpleCache/get.mdx
I'd like to suggest removing  `render(path)` function definition since it's not being used in the example.
> fix: remove unused lines of code from docs for SimpleCache/get.mdx

- runtime/spidermonkey/build-engine.sh
For build environments where rustc is already installed but rustup is missing, trust that the compiler being able to target `wasm32-wasi` is enough.
> chore: Detect if there's already a rustc installed that can target wasm32-wasi

- runtime/js-compute-runtime/.gitignore
- runtime/js-compute-runtime/Makefile
- runtime/js-compute-runtime/mk/commands.mk
Instead of copying build outputs into the source tree, produce a single archive in the build directory and copy the final result out. This allows us to maintain a debug and release build in the build directory, avoiding unnecessary rebuilds.
This will require some changes in downstream consumers, as the `shared-builtins` target now produces a single `shared.a` archive in the current directory, instead of copying multiple archives out into the `shared` directory.
> chore: Rework the shared-builtins target to produce a single static archive

- .gitmodules
- runtime/js-compute-runtime/Makefile
- runtime/js-compute-runtime/builtins/crypto-algorithm.cpp
- runtime/js-compute-runtime/mk/commands.mk
Add a submodule for fmtlib 10.1.1 and port some uses of string concatenation to
`fmt::format` instead.
If we start using fmtlib in any of the shared builtins, we'll need to ensure that the `third_party/fmt/src/format.o` file gets included when we construct `shared.a`.
> chore: Add fmtlib

- integration-tests/cli/build-config.test.js
- src/bundle.js
This implements the [recently specified](https://runtime-keys.proposal.wintercg.org/#fastly) `"fastly"` condition when building the JS runtime app.
We should also roll this configuration out to any Webpack or esbuilds in boilerplates and starter kits for Fastly, but this will provide the first-class support in the runtime at least.
> feat: implement the "fastly" condition

- runtime/js-compute-runtime/Makefile
The original build of openssl was missing the `-O3` config option, which meant that we've been using an un-optimized version. Adding `-O3` cuts out nearly 3Mb from the resulting wasm blob, going from a little over 12Mb to 9.6Mb. Additionally, this will probablly improve compile time for javascript, as there will be less optimization fodder for cranelift to chew through.
> chore: Build openssl with -O3

- .vscode/c_cpp_properties.json
- integration-tests/js-compute/fixtures/crypto/bin/index.js
- integration-tests/js-compute/fixtures/crypto/tests.json
- runtime/js-compute-runtime/builtins/crypto-algorithm.cpp
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
In the last release we added support for importing an ECDSA key with SubtleCrypto.prototype.importKey. This patch adds the ability to use these keys to sign data and to verify data was signed with the same underlying key.
With this patch, Fastly Compute customers are now able to validate signatures provided by Fastly Fanout requests
fixes #663 
Here is an example of how a Fastly Customer can verify Fastly Fanout requests:
<https://fanout-cf.edgecompute.app/>
```js
/// <reference types="@fastly/js-compute" />
import { createFanoutHandoff } from "fastly:fanout";
import { env } from 'fastly:env';
import { importJWK, jwtVerify } from "jose";
// A JWK version of the public key documented on https://developer.fastly.com/learning/concepts/real-time-messaging/fanout/#validating-grip-requests …
```
> feat: add support for ECDSA keys to be used with SubtleCrypto.prototype.sign and SubtleCrypto.prototype.verify

- integration-tests/js-compute/fixtures/app/src/dynamic-backend.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/js-compute-runtime/builtins/backend.cpp
- runtime/js-compute-runtime/builtins/backend.h
- runtime/js-compute-runtime/error-numbers.msg
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
- runtime/js-compute-runtime/host_interface/fastly.h
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
This adds new methods to the `Backend` class which enable the application to retrieve information about any backend, this is particularly useful for checking if the backend is "healthy".
Added:
> feat: Add Backend.exists, Backend.fromName, Backend.isHealthy, and Backend.prototype.toName

- documentation/docs/fastly:cache/SimpleCache/getOrSet.mdx
Hopefully clarifies that the function argument is called if and only if the key is not present in the cache.
> ✏ Tighten up docs for `SimpleCache.getOrSet`

- documentation/docs/fastly:kv-store/KVStore/prototype/put.mdx
The code at Examples section gives me an error log below;
```
stderr | c8285363 | Error while running request handler: put: At least 2 arguments required, but only 1 passed
stderr | c8285363 | Stack:
stderr | c8285363 |   app@<stdin>:9:31
stderr | c8285363 |   async*@<stdin>:12:58
```
This can be fixed by changing the following put() call to get()
```
const entry = await files.put('hello')
```
Sorry for pointing out nit-picking error all the time, I just ran into this error today when I joined a workshop at a local site.
> Fix a documentation bug in KVStore.prototype.put

- runtime/js-compute-runtime/builtins/kv-store.cpp
- runtime/js-compute-runtime/builtins/kv-store.h
- runtime/js-compute-runtime/core/event_loop.cpp
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
- runtime/js-compute-runtime/host_interface/fastly.h
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
We model the JS API for KVStore methods as async promise-returning methods however, the internal implementation is currently synchronous due to the host-call itself being synchronous.
This patch updates our implementation to use the new asynchronous host-call for KVStore lookups.
The great thing about this change, is it is not a user-facing API change as we were already returning a Promise. This PR makes that Promise resolution happen asynchronously ☺️
> fix: Make the underlying KVStore.prototype.get implementation be async

- types/globals.d.ts
This PR adds `URL` as an allowed type for the first parameter of the `fetch()` function in the TypeScript type definitions.
The parameter is listed in MDN to be anything that is a string or has a stringier, including URL.
The functionality seems to already be there in the runtime.
Node.js's typings has RequestInfo | URL.
Currently if you write a program that happens to load both typings and there isn't a way around it, then if you pass a URL to the fetch() function, it will think you're calling Node.js's fetch and not ours, so this would be a usability fix.
> fix: Allow URL as input on fetch() on TypeScript typings for compat with Node.js

- integration-tests/js-compute/fixtures/app/src/dynamic-backend.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
Previously we were not setting the fields in the bitmask to indicate to Fastly Compute that these fields should be read
> fix: ensure we honor first-byte-timeout and between-bytes-timeout for dynamically registered backends

- runtime/js-compute-runtime/builtins/request-response.cpp
- types/globals.d.ts
This fixes https://github.com/fastly/js-compute-runtime/issues/716
> fix: If request does not have a static backend defined, return `undefined` for the Request.prototype.backend getter

- .github/workflows/release-please.yml
Add a step to the `release-please.yml` GitHub Actions workflow that publishes to the Fastly internal GItHub package registry [as discussed in Slack](https://fastly.slack.com/archives/C022F76SJ83/p1707421784242279).
> Add step to publish to GitHub package registry

- documentation/docs/fastly:edge-rate-limiter/PenaltyBox/PenaltyBox.mdx
- documentation/docs/fastly:edge-rate-limiter/PenaltyBox/prototype/add.mdx
- documentation/docs/fastly:edge-rate-limiter/PenaltyBox/prototype/has.mdx
- integration-tests/js-compute/fixtures/app/src/edge-rate-limiter.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/js-compute-runtime/builtins/edge-rate-limiter.cpp
- runtime/js-compute-runtime/builtins/edge-rate-limiter.h
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
- src/bundle.js
- types/edge-rate-limiter.d.ts
This builds on top of https://github.com/fastly/js-compute-runtime/pull/730 and adds a JavaScript implementation for the penalty-box feature of the edge-rate-limiter host functionality
> feat: Add a PenaltyBox JavaScript Class which can be used standalone for adding and checking if an entry is in the penalty-box

- documentation/docs/fastly:edge-rate-limiter/EdgeRateLimiter/EdgeRateLimiter.mdx
- documentation/docs/fastly:edge-rate-limiter/EdgeRateLimiter/prototype/checkRate.mdx
- integration-tests/js-compute/fixtures/app/src/edge-rate-limiter.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/js-compute-runtime/builtins/edge-rate-limiter.cpp
- runtime/js-compute-runtime/builtins/edge-rate-limiter.h
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.h
- runtime/js-compute-runtime/js-compute-builtins.cpp
- src/bundle.js
- types/edge-rate-limiter.d.ts
This is the final PR for the Edge Rate Limiter functionality 🎉 
The end result allows programs such as the one below to run as expected:
```js
import { RateCounter, PenaltyBox, EdgeRateLimiter } from 'fastly:edge-rate-limiter';
addEventListener("fetch", event => {
const rc = new RateCounter('rc')
const pb = new PenaltyBox('pb')
const erl = new EdgeRateLimiter(rc, pb)
const entry = event.client.address;
const delta = 1;
const window = 10; // seconds
const limit = 100;
const timeToLive = 5; // minutes
const blocked = erl.checkRate(entry, delta, window, limit, timeToLive);
let response;
if (blocked) {
response =  new Response(`${entry} was blocked`)
} else {
response =  new Response(`${entry} was not blocked`)
}
event.respondWith(response)
})
```
> feat: Add a EdgeRateLimiter JavaScript Class which enables edge-rate-limiting by utilising a RateCounter and a PenaltyBox instance

- documentation/docs/fastly:dictionary/Dictionary/Dictionary.mdx
- documentation/docs/fastly:dictionary/Dictionary/prototype/get.mdx
- documentation/versioned_docs/version-1.13.0/fastly:dictionary/Dictionary/Dictionary.mdx
- documentation/versioned_docs/version-1.13.0/fastly:dictionary/Dictionary/prototype/get.mdx
- documentation/versioned_docs/version-2.5.0/fastly:dictionary/Dictionary/Dictionary.mdx
- documentation/versioned_docs/version-2.5.0/fastly:dictionary/Dictionary/prototype/get.mdx
- documentation/versioned_docs/version-3.10.0/fastly:dictionary/Dictionary/Dictionary.mdx
- documentation/versioned_docs/version-3.10.0/fastly:dictionary/Dictionary/prototype/get.mdx
- types/config-store.d.ts
- types/dictionary.d.ts
Dictionary has been deprecated on Fastly Compute for a long time, we forgot to document that in the JavaScript Compute SDK
We intended to do this change in 0.5.4 (https://github.com/fastly/js-compute-runtime/blob/main/CHANGELOG.md#054-2022-09-28) when we added ConfigStore but we forgot to update the documentation
> docs: deprecate the Dictionary Class and advice applications to use the ConfigStore class

- types/globals.d.ts
This PR corrects the type of Headers.prototype.values() so it returns an `IterableIterator<string>`. Previously it was  incorrectly marked to return a `IterableIterator<[string]>`
As described here (https://js-compute-reference-docs.edgecompute.app/docs/globals/Headers/prototype/values), `Headers.prototype.values()` should return an iterator whose values are `string`, not of type `[string]`.
Internally it also seems to be `IterableIterator<string>`; I've checked that code like this works correctly:
```javascript
for (const value of event.request.headers.values()) {
console.log(typeof value, value);
}
```
I couldn't find a test for this type so this only includes the corrected type file.
> fix: correct type definition of Headers.prototype.values() to indicate it returns an IterableIterator<string>

- integration-tests/cli/help.test.js
- js-compute-runtime-cli.js
- src/bundle.js
- src/compileApplicationToWasm.js
- src/enableTopLevelAwait.js
- src/parseInputs.js
- src/precompile.js
- src/printHelp.js
This PR is a fix for #729
These fixes were enough to get top-level-await in both my main module and dependencies working for me.
I would love to add a test suite, but wasn't able to figure out how to do it. Does the setup require a linux machine like it says in the DEVELOPING readme file? I'm on a Mac...
The following minimal case works (requires `"type": "module"` in `package.json`):
src/index.js
```javascript
/// <reference types="@fastly/js-compute" />
import { foo } from './dep.js';
const value = await foo();
addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));
async function handleRequest(event) {
return new Response(value, { status: 200 }); // returns 'bar'
}
```
src/dep.js
```javascript
export async function wait() {
return Promise.resolve();
}
await …
```
> feat: add new flag --experimental-enable-top-level-await

- package.json
Node v20 comes bundled with NPM v10, [as per their release page](https://nodejs.org/en/about/previous-releases#looking-for-latest-release-of-a-version-branch).
Otherwise, consumers get a warning when installing the package:
```sh
❯ npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@fastly/js-compute@3.7.0',
npm WARN EBADENGINE   required: { node: '16 - 20', npm: '^8 || ^9' },
npm WARN EBADENGINE   current: { node: 'v20.12.1', npm: '10.5.0' }
npm WARN EBADENGINE }
```
> fix: declare support for npm 10

- DEVELOPMENT.md
I've been able to build the runtime from source on Apple Silicon, so this PR adds the steps to `DEVELOPMENT.md`.
I have seen that the tests in `integration-tests/js-compute/` pass using the runtime that results from the build, both in local and server modes.
My setup is:
2021 M1 MacBook Pro 16-inch
CPU M1 Pro, 32GB RAM
macOS Sonoma 14.4.1 (23E224)
> Instructions for building on macOS on Apple Silicon

- integration-tests/js-compute/fixtures/app/src/dynamic-backend.js
- integration-tests/js-compute/fixtures/app/tests.json
- test-d/.test-d.ts
- types/globals.d.ts
This field never existed in the released version of our Backend implementation, it is a remnant of a previous approach I was taking, I somehow forgot to remove the tests and type definition
The tests were all checking to see that the constructor did not throw, which it wouldn't because it has zero knowledge about this made up field...
> fix: correct type definition for the global BackendConfiguration type - there is no `checkCertificate` field

- documentation/docs/fastly:kv-store/KVStore/prototype/delete.mdx
- integration-tests/js-compute/fixtures/app/src/kv-store.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/js-compute-runtime/builtins/kv-store.cpp
- runtime/js-compute-runtime/builtins/kv-store.h
- runtime/js-compute-runtime/builtins/request-response.cpp
- runtime/js-compute-runtime/builtins/request-response.h
- runtime/js-compute-runtime/core/event_loop.cpp
- runtime/js-compute-runtime/core/event_loop.h
- runtime/js-compute-runtime/error-numbers.msg
- runtime/js-compute-runtime/js-compute-builtins.cpp
refactor our async task implementation to be a generic AsyncTask class instead of separate implementations for each async operation
This implementation enables our event loop to no longer have to be aware of all the different async tasks and how to process them, instead it understands AsyncTask and to call the `process` function contained within an AsyncTask.
A side-effect of this refactoring is that KVStore.prototype.lookup and KVStore.prototype.delete now work when being called multiple times in parallel - previously this would not work as the KVStore class contained a slot for the Promise of the async work, which meant if you called either method more than once, the previous method's Promise would have been overwritten within the Slot. The new implementation creates a new AsyncTask …
>  fix: ensure multiple KVStore lookups and deletes can happen at the same time 

- integration-tests/js-compute/test.js
- package.json
Node.js 22 is now current. This fixes and updates the tests to run in Node.js 22.
This also removes the `"engines"` field restriction in the package.json that warns when installing for newer versions of Node.js and npm. Node.js has good backwards compat that it should be fine to run old js-compute-runtime versions on newer Node.js and npm versions without warning. If the problem is that the js-compute-runtime version is old, that is a property of that release, not the version of Node.js or npm it is being run against.
> Node.js 22 support

- types/globals.d.ts
In #639 we added support for ECDSA keys in SubtleCrypto. This adds the
interface to the type defintions for SubtleCrypto.importKey to allow
consuming TypeScript applications to use this type of key. Partly
addresses #579 and brings the library in sync with [our Fanout docs][1], and the library's [reference docs][2].
[1]: https://www.fastly.com/documentation/guides/concepts/real-time-messaging/fanout/#validating-grip-requests
[2]: https://js-compute-reference-docs.edgecompute.app/docs/globals/SubtleCrypto/prototype/importKey#parameters
> Add EcKeyImportParams to SubtleCrypto.importKey

- integration-tests/js-compute/fixtures/app/setup.js
- integration-tests/js-compute/fixtures/app/src/kv-store.js
- integration-tests/js-compute/fixtures/app/tests.json
- integration-tests/js-compute/test.js
This adds an integration test for passing a request body to the kvstore `put`.
> Integration test for passing a request body to kv-store put

- integration-tests/js-compute/fixtures/app/src/request-cache-key.js
- runtime/fastly/builtins/fetch/request-response.cpp
- runtime/js-compute-runtime/builtins/request-response.cpp
Adds support for `cacheKey` in `Request` initialization, which was previously omitted, and fixes the test case that was supposed to test for this.
We don't use an internal slot for `cacheKey` since it is effectively a header-manipulating function, where that header manipulation is observable to users. If we want to use an internal slot, that would be a breaking change at this point to provide a header alteration from such a slot that exists only as observable to the host.
Note that this is implemented in the parallel StarlingMonkey branch while this port is in progress... a fact of life during this port process!
Resolves https://github.com/fastly/js-compute-runtime/issues/768.
> fix: support cacheKey in Request init

- documentation/docs/fastly:cache/TransactionCacheEntry/update.mdx
The docs page for `TransactionCacheEntry.update` was incorrectly titled `TransactionCacheEntry.insert`
https://js-compute-reference-docs.edgecompute.app/docs/fastly:cache/TransactionCacheEntry/update
This PR simply fixes this. As a result, the left-side TOC is also corrected.
> docs: Correct page title for TransactionCacheEntry.update

- .github/workflows/main.yml
- CHANGELOG.md
The release is currently failing because the CHANGELOG generation is outputting the version headings as URLs.
Release please seems to default to outputting the version headings as URLs now which seems useful as well.
This PR updates the existing CHANGELOG to use version heading URLs and also disables the changelog checker based on the assumption that we have enough evidence at this point to trust the output from release please.
In addition, the changelog checker doesn't seem to have an option to disable version URL checks.
For now this leaves the changelog checker in the repo in case we want to change this back in future, if it can support this or if we find a release please option to disable the version URL links (which I was unable to), but we could remove it entirely as well.
This PR …
> changelog: version links, disable checker for version links

- .github/workflows/main.yml
- documentation/docs/fastly:dictionary/Dictionary/prototype/get.mdx
- documentation/versioned_docs/version-3.14.0/fastly:dictionary/Dictionary/prototype/get.mdx
The release failed at the docs publish stage, although every other part succeeded - release creation, publish etc.
This fixes the docs issue, and also adds a new workflow to fail the release sooner if the documentation has a build issue.
Would be great to post this up as a patch asap.
> docs: fix documentation build

- .github/workflows/main.yml
- CHANGELOG.md
This reverts https://github.com/fastly/js-compute-runtime/pull/780 as it turns out we need to maintain this changelog structure for our feeds.
For future reference - the automatic release PRs require the changelog to be manually modified.
Will post out a release with this asap.
> fix: revert changelog heading changes

- integration-tests/js-compute/fixtures/app/src/cache-core.js
- integration-tests/js-compute/fixtures/app/src/timers.js
- integration-tests/js-compute/fixtures/app/tests-skip-starlingmonkey.json
- integration-tests/js-compute/fixtures/app/tests.json
- integration-tests/js-compute/test.js
- runtime/fastly/host-api/host_api.cpp
- runtime/js-compute-runtime/host_interface/host_api.cpp
This integrates Fastly support for timers on top of the new `deadline()` hook on AsyncTask for StarlingMonkey, which is supported by StarlingMonkey timers.
Timers are represented by a handle that is never used in Fastly's host call model. When encountering a timer in the select host hook we check its deadline and progress it if it is ready. We also bound the select call timeout now by the least deadline when timer tasks are present, as we previously implemented.
This architecture also exposes an implementation gap in that setting timers when no other async tasks were pending would never resolve. Without any other primitives to work with a busy loop is implemented in this case to properly support real timeouts and a new test is added. Alternatively, we could throw an error here but I …
> Starlingmonkey timers

- runtime/fastly/host-api/host_call.cpp
- runtime/js-compute-runtime/host_interface/host_call.cpp
The message for a limit-exceeded error was missing trailing spaces for a multi-line string, resulting in some words being concatenated together.
> fix: Fix string formatting for limit-exceeded errors

- runtime/fastly/builtins/fastly.cpp
- runtime/js-compute-runtime/js-compute-runtime.cpp
This adds an out of memory callback to SpiderMonkey to log the error to stderr.
The message logged is `Critical Error: out of memory`.
> feat: add out-of-memory callback with stderr log

- .github/workflows/starlingmonkey.yml
- integration-tests/js-compute/fixtures/app/tests-skip-starlingmonkey.json
- integration-tests/js-compute/test.js
- package.json
- runtime/fastly/builtins/cache-core.cpp
- runtime/fastly/builtins/fetch/request-response.cpp
- runtime/fastly/handler.cpp
- runtime/js-compute-runtime/builtins/cache-core.cpp
- tests/wpt-harness/build-wpt-runtime.sh
This completes the StarlingMonkey SDK test suite, enabling all of the tests for the StarlingMonkey build and on CI.
We still need to enable the WPT though, which still has tests outstanding.
In the process a new test filtering command has been added making it possible to run local integration tests via `npm run test:integration -- --starlingmonkey --local test-name` for example.
> Complete StarlingMonkey SDK Tests

- runtime/fastly/host-api/component/fastly_world_adapter.cpp
- runtime/js-compute-runtime/host_interface/component/fastly_world_adapter.cpp
Fix issues in some host calls where a buffer length error was being handled by reallocating to the new buffer size, but was discarding the new buffer's pointer. This should also fix flaky tests in CI.
It's unfortunate that `cabi_realloc` can't be marked `[[nodiscard]]`, as it's defined within an `extern "C"` block.
> fix: Fix uses of cabi_realloc that were discarding their results

- documentation/app/src/index.js
Unfortunately https://github.com/fastly/js-compute-runtime/pull/825 broke our documentation site build.
Posting this patch release out now to resolve the issue and get the docs site back up.
> fix: documentation site build

- documentation/docs/fastly:logger/Logger/Logger.mdx
- documentation/docs/fastly:logger/Logger/prototype/log.mdx
When https://github.com/fastly/js-compute-runtime/pull/804 landed, this functionality changed but we missed the note in the website documentation, this commit updates the notes.
The Logger constructor as it can now be used during build-time initialisation and the Logger.prototype.log method can not be used during build-time initialisation
> fix: correct the documentation for the fastly:logger module

- tests/wpt-harness/expectations-sm/html/webappapis/structured-clone/structured-clone.any.js.json
- tests/wpt-harness/expectations/html/webappapis/structured-clone/structured-clone.any.js.json
This is a draft as we want to always keep the SpiderMonkey version used in our version of StarlingMonkey to be the same as the version used when not using StarlingMonkey
I've gone ahead and done the equivalent [pull-request for spidermonkey-wasi-embedding](https://github.com/bytecodealliance/spidermonkey-wasi-embedding/pull/13) -- once that lands, I will open one for StarlingMonkey and when that lands, we can go ahead and update StarlingMonkey on this branch and then this pull-request will be ready to land also 👍 
Our patches:
Bring back JS Streams
Add BYOB Streams
Re-add signal handling fix for WASI to fdlibm
JSAPI support for resetting the seed for Math.random() Add JS::HasJobsPending
Respect js::ClassSpec::DontDefineConstructor in DefineConstructorAndPrototype
This work was done in …
> Update to SpiderMonkey v127.0.2

- types/globals.d.ts
I've got `src/index.ts(6,15): error TS2304: Cannot find name 'performance'.` error with the following code used in the TypeScript starter kit;
```js
/// <reference types="@fastly/js-compute" />
addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));
async function handleRequest(event: FetchEvent) {
console.log(performance.now());
return new Response("Hello", {
status: 200,
});
}
```
This PR solves the aforementioned error.
> fix: add type definitions of Performance APIs

- integration-tests/cli/non-existent-engine-wasm-path.test.js
- integration-tests/cli/non-existent-input-path.test.js
- src/compileApplicationToWasm.js
Fixes the spelling of the word "non-existent" in the CLI
> fix: correct spelling in CLI error message

- runtime/fastly/builtins/fetch-event.h
- runtime/js-compute-runtime/builtins/client-info.h
It is currently named `FetchEvent`, which can lead to confusion when logging out the value. For example this application logs the client info prototype and the fetch event prototype:
```js
addEventListener("fetch", event => event.respondWith(handleRequest(event)))
async function handleRequest(event) {
console.log(event.client.__proto__)
console.log(event.__proto__)
return new Response;
}
```
The log lines look like this:
```
Log: FetchEvent { address: [Getter], geo: [Getter], tlsCipherOpensslName: [Getter], tlsProtocol: [Getter], tlsJA3MD5: [Getter], tlsClientCertificate: [Getter], tlsClientHello: [Getter] }
Log: FetchEvent { client: [Getter], request: [Getter], respondWith: [ function respondWith() {[native code]}], waitUntil: [ function waitUntil() {[native code]}] }
```
We can see that …
> fix: Correct Class name for the ClientInfo class

- .github/actions/compute-sdk-test/action.yml
- .github/actions/e2e/action.yml
- .github/workflows/main.yml
- integration-tests/cli/disable-starlingmonkey.test.js
- integration-tests/js-compute/fixtures/app/setup.js
- integration-tests/js-compute/fixtures/app/src/kv-store.js
- integration-tests/js-compute/test.js
- package.json
- runtime/fastly/build-debug.sh
- runtime/fastly/build-release.sh
- runtime/js-compute-runtime/Makefile
- src/parseInputs.js
This switches the default engine used by js-compute-runtime to be the StarlingMonkey engine, with a new `--disable-starlingmonkey` flag which can be used to revert back to the js-compute-runtime.wasm engine.
* When using `--disable-starlingmonkey`, the message `"Building with the js-compute-runtime.wasm engine"` is printed during the build.
* The `--starlingmonkey` flag continues to work as a noop, but no longer logs that the experimental StarlingMonkey engine is being used.
* The `fastly.sdkVersion` is now `x.y.z` for the StarlingMonkey build and `x.y.z-legacy` for the non-StarlingMonkey build under `--disable-starlingmonkey`.
This is marked as a feature commit, as the hope is that we can achieve this as a minor release.
Working through the risk analysis here:
1. All test coverage is …
> feat: use StarlingMonkey by default, --disable-starlingmonkey flag

- runtime/js-compute-runtime/builtins/edge-rate-limiter.cpp
Previously we were getting lucky because we used `RateCounter::get_name` and RateCounter and PenaltyBox both stored there name within slot 0
> fix: When constructing an EdgeRateLimiter, retrieve the PenaltyBox instance's name using PenaltyBox::get_name

- .github/workflows/main.yml
- ci/clang-format.sh
- runtime/js-compute-runtime/builtins/transform-stream-default-controller.h
Ensures we use the clang-format that ships with the versioned wasi-sdk we use (and any other clang-format as different versions can format differently, which is a pain to deal with)
>  use clang-format included from wasi-sdk 

- .github/workflows/main.yml
- integration-tests/js-compute/test.js
Ensures our StarlingMonkey jobs in CI use the branch name as part of the app name, previously they were just called app---sm, which meant two different pull-requests would deploy to the same application, causing confusing CI test failures
> ensure ci uses the branch name in the deployed fastly service for the starlingmonkey test app

- .github/workflows/main.yml
We change the concurrency cancelling logic from applying to the whole workflow to instead being applied to individual jobs in the workflow, except for the build job, which we want to always run
> CI: Always run the build job, never cancel it

- runtime/fastly/builtins/fetch-event.cpp
- runtime/fastly/builtins/fetch-event.h
- runtime/fastly/handler.cpp
This splits our dispatch_fetch_event into two implementations:
- The first one which does the fetch event handling logic
- The second one sets up timers and calls the first one, printing how long it took
Most applications do not have debug logging enabled, and by splitting the functions up like this it means that during wizening time, it should remove the function which does the timing as it wouldn't be used
> perf: only time the fetch event when debug logging is enabled

- integration-tests/cli/build-config.test.js
- integration-tests/cli/custom-input-path.test.js
- integration-tests/cli/custom-output-path.test.js
- integration-tests/cli/disable-starlingmonkey.test.js
- integration-tests/cli/engine-wasm-path-is-not-a-file.test.js
- integration-tests/cli/help.test.js
- integration-tests/cli/input-path-is-not-a-file.test.js
- integration-tests/cli/invalid.test.js
- integration-tests/cli/non-existent-engine-wasm-path.test.js
- integration-tests/cli/non-existent-input-path.test.js
- integration-tests/cli/output-path-is-not-a-file.test.js
- integration-tests/cli/valid.test.js
- integration-tests/cli/version.test.js
- package.json
- src/printHelp.js
- src/printVersion.js
Still keep the current name for backwards compatiblity, but also include a new short name.
Update the CLI help and version output to use whichever name was used when executing the file.
Below show how the output uses the correct name:
```
❯ npx js-compute --help
js-compute 3.19.0
USAGE:
js-compute [FLAGS] [OPTIONS] [ARGS]
FLAGS:
-h, --help                                              Prints help information
-V, --version                                           Prints version information
OPTIONS:
--engine-wasm <engine-wasm>                             The JS engine Wasm file path
--enable-experimental-high-resolution-time-methods      Enable experimental high-resolution fastly.now() method
--enable-experimental-top-level-await                   Enable experimental top level await
ARGS: …
```
> feat: Add new CLI name of `js-compute` which matches the published package name `@fastly/js-compute`

- .github/workflows/main.yml
- .gitignore
- integration-tests/js-compute/test.js
- package.json
- runtime/fastly/build-debug.sh
- src/parseInputs.js
This strips the debug relocation sections from the debug build, and only leaves the names, giving a 29MB debug build (in comparison to the 8.8MB release build and over 200MB full debug build).
I've verified an unreachable assertion, and the function names get output to the stack correctly on this build, just without line numbers.
In addition, instead of writing to the same `starling.wasm` the debug build now writes to `starling.debug.wasm` in preparation for being able to ship the debug build.
A new `--debug-build` CLI option is added, which throws `"Debug builds are not currently available for published releases"` for now.
When we remove the old js-compute-runtime.wasm build, then that would be a good time to start shipping our debug build by default.
Should resolve the current CI issues …
> StarlingMonkey debug build with names section only

- .github/workflows/main.yml
- .github/workflows/release-please.yml
- integration-tests/cli/help.test.js
- integration-tests/js-compute/test.js
- js-compute-runtime-cli.js
- package.json
- runtime/fastly/build-release-weval.sh
- src/compileApplicationToWasm.js
- src/parseInputs.js
- src/printHelp.js
- yarn.lock
This PR pulls in my work to use "weval", the WebAssembly partial evaluator, to perform ahead-of-time compilation of JavaScript using the PBL interpreter we previously contributed to SpiderMonkey. This work has been merged into the BA fork of SpiderMonkey in
bytecodealliance/gecko-dev#45,  bytecodealliance/gecko-dev#46, bytecodealliance/gecko-dev#47, bytecodealliance/gecko-dev#48, bytecodealliance/gecko-dev#51, bytecodealliance/gecko-dev#52, bytecodealliance/gecko-dev#53, bytecodealliance/gecko-dev#54, bytecodealliance/gecko-dev#55, and then integrated into StarlingMonkey in bytecodealliance/starlingmonkey#91.
The feature is off by default; it requires a `--enable-experimental-aot` flag to be passed to `js-compute-runtime-cli.js`. This requires a separate build of the engine Wasm module to …
> Experimental: add ahead-of-time compilation via weval and PBL.

- .github/workflows/main.yml
This PR pulls in bytecodealliance/starlingmonkey#106, which in turn pulls in bytecodealliance/spidermonkey-wasi-embedding#21, which in turn pulls in bytecodealliance/gecko-dev#57, to fix a bug in weval'd PBL execution (AOT compilation mode) for `TableSwitch` opcodes.
> Update StarlingMonkey to pull in PBL+weval updates in SpiderMonkey.

- integration-tests/js-compute/fixtures/app/src/cache-core.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/cache-core.cpp
- runtime/js-compute-runtime/builtins/cache-core.cpp
Fixes the header lookup for the core-cache functions.
A smaller version of the same fixes in https://github.com/fastly/js-compute-runtime/pull/885 without conflicts against https://github.com/fastly/js-compute-runtime/pull/844.
> fix: core-cache headers case

- tests/wpt-harness/run-wpt.mjs
It turns out that when an entire test path is not reported, this error does not propagate to failing the entire WPT run.
This resolves that by adding to the missing test count, either the expectation count or if there is no expectations file, at least one missing test.
Found in StarlingMonkey in https://github.com/bytecodealliance/StarlingMonkey/pull/107.
> fix handling of missing WPT results

- .github/workflows/main.yml
- package.json
- runtime/fastly/builtins/fetch/headers.cpp
- runtime/fastly/builtins/fetch/request-response.cpp
- runtime/fastly/common/sequence.hpp
- tests/wpt-harness/expectations-sm/fetch/api/headers/headers-errors.any.js.json
Enables the StarlingMonkey debug build, updating the StarlingMonkey version in the process.
Inlines `sequence.hpp` just pending https://github.com/fastly/js-compute-runtime/pull/844 which then updates to the new validation structure.
This caught a bug with our headers value validation, where a rope string was not being linearized and failing the debug build. This is fixed by explicitly forcing linearization per https://searchfox.org/mozilla-central/source/js/public/String.h#196. The new failure has then exposed an underlying bug which required two tests to be marked as failing, but this is correct since the bug exists in the current implementation but is just masked by this new failure, but this is also addressed in #844 when that lands.
Specifically the error is that the error thrown for …
> ci: StarlingMonkey WPT debug build

- .github/workflows/main.yml
Now that we're no longer running the js-compute-runtime tests, this expands the compute CI tests to include the Weval and release builds.
> ci: include weval and release builds for compute

- integration-tests/cli/help.test.js
- package.json
- src/parseInputs.js
- src/printHelp.js
This includes the debug build now that we no longer ship the js-compute-runtime builds.
The current build sizes are 10MB each for the Weval and main StarlingMonkey engines.
This debug build adds an additional 30MB to the package so the npm package will go from ~25MB to ~55MB.
In general, packages up to 100MB are not a problem in the npm ecosystem, and the benefit of this will be having a path for users to provide stack traces on panics, which would be highly beneficial for investigating bug reports.
> feat: ship --debug-build CLI flag as public

- integration-tests/js-compute/fixtures/app/fastly.toml.in
- js-compute-runtime-cli.js
- src/addSdkMetadataField.js
- src/compileApplicationToWasm.js
- src/parseInputs.js
This removes the former experimental `--enable-pbl` flag now that we have the new `--enable-experimental-aot` flag.
As an experimental undocumented flag it is deemed acceptable to remove outside of a major change, but will still be noted as a deprecation in the release notes.
//cc @cfallin
> deprecate: remove experimental --enable-pbl flag

- .github/workflows/release-please.yml
- package.json
Unfortunately the 3.21.0 publish failed due to missing the new `fastly-ics.wevalcache` file in the package.json files listing. This fixes that for a fast-track 3.21.1 patch, and also updates the publish workflow to perform debug, release and weval builds in parallel.
> fix: missing publish file, parallel publish build

- integration-tests/js-compute/compare-downstream-response.js
- integration-tests/js-compute/fixtures/app/src/assertions-throwing.js
- integration-tests/js-compute/fixtures/app/src/device.js
- integration-tests/js-compute/fixtures/app/src/index.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/device.cpp
Resolves a bug where `Device.toJSON()` would always return `null` for all `isDesktop()` style boolean properties as well as for `hardwareType`.
In the process I also refactored the test file to simplify the error handler hoping to do this as I touch each file going forward.
> fix: Device.toJSON() properties

- .github/workflows/main.yml
- integration-tests/js-compute/compare-downstream-response.js
- integration-tests/js-compute/fixtures/app/src/dynamic-backend.js
- integration-tests/js-compute/fixtures/app/src/response.js
- integration-tests/js-compute/fixtures/app/tests.json
- integration-tests/js-compute/test.js
- runtime/fastly/builtins/config-store.cpp
- runtime/fastly/handler.cpp
This adds a test for an event loop stall and ensures that it is just a warning instead of being a panic, so that it is distinguished from critical runtime errors / internal errors.
I also refactored the JS test runner to have some options for how to stream the response body while investigating some tests cases around this even if I didn't use this full functionality in the end.
This also includes a couple of recent Starlingmonkey patches that improve error outputs here - (https://github.com/bytecodealliance/StarlingMonkey/pull/132, https://github.com/bytecodealliance/StarlingMonkey/pull/139).
> Update event loop stall error as no longer a panic

- package-lock.json
- package.json
This includes a fix for irreducible control flow; see [this PR](https://github.com/cfallin/waffle/pull/13) in waffle.
> AOT compilation: update to weval 0.2.12.

- package-lock.json
- package.json
This pulls in a fix to weval's CI so that Intel Macs (`x86-64-macos` target) get x86-64 binaries, not aarch64 binaries.
> Update to weval 0.2.14.

- .github/workflows/main.yml
- documentation/docs/fastly:runtime/purgeSurrogateKey.mdx
- documentation/docs/fastly:runtime/vCpuTime.mdx
- integration-tests/js-compute/compare-downstream-response.js
- integration-tests/js-compute/fixtures/app/src/runtime.js
- integration-tests/js-compute/fixtures/app/tests.json
- integration-tests/js-compute/fixtures/tla/tests.json
- integration-tests/js-compute/test.js
- runtime/fastly/builtins/cache-simple.cpp
- runtime/fastly/builtins/fastly.cpp
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
- src/bundle.js
- types/runtime.d.ts
This resolves https://github.com/fastly/js-compute-runtime/issues/923 in adding support for a `purgeSurrogateKey` call which takes a key string and an optional soft purge boolean.
This is added to `fastly:runtime` in the spirit of this new import subsystem replacing the Fastly global, which currently mostly mirrors `fastly:experimental` anyway. The purge host call itself is refactored to move into the `host_api::Runtime` namespace as part of this process.
This PR also refactors the test.json usage to default the request and response and environment properties to avoid unnecessary repetition.
> feat: expose purgeSurrogateKey hostcall

- .github/workflows/main.yml
- integration-tests/js-compute/compare-downstream-response.js
- integration-tests/js-compute/fixtures/app/src/response.js
- integration-tests/js-compute/fixtures/app/tests.json
This adds a test case for passing a response body directly to a new request body, fixing a bug upstream in StarlingMonkey in https://github.com/bytecodealliance/StarlingMonkey/pull/143.
> fix: passing direct response body to requests in streaming

- integration-tests/js-compute/fixtures/app/src/compute.js
- package-lock.json
- package.json
- src/compileApplicationToWasm.js
This update pulls in the latest changes, mainly revolving around weval's move to the Bytecode Alliance as a Hosted Project, in its new repository at [bytecodealliance/weval](https://github.com/bytecodealliance/weval).
> Update to weval 0.3.2.

- documentation/docs/compute/vCpuTime.mdx
Corrects `undefined` return in docs to `number`.
> docs: correct vCpuTime return type

- .github/workflows/main.yml
- documentation/docs/geolocation/getGeolocationForIpAddress.mdx
- integration-tests/js-compute/fixtures/app/.eslintrc.cjs
- integration-tests/js-compute/fixtures/app/setup.js
- integration-tests/js-compute/fixtures/app/src/assertions.js
- integration-tests/js-compute/fixtures/app/src/cache-override.js
- integration-tests/js-compute/fixtures/app/src/device.js
- integration-tests/js-compute/fixtures/app/src/fanout.js
- integration-tests/js-compute/fixtures/app/src/geoip.js
- integration-tests/js-compute/fixtures/app/src/index.js
- integration-tests/js-compute/fixtures/app/src/timers.js
- integration-tests/js-compute/fixtures/app/teardown.js
- integration-tests/js-compute/fixtures/app/tests.json
- integration-tests/js-compute/fixtures/tla/.eslintrc.cjs
- integration-tests/js-compute/fixtures/tla/src/assertions.js
- integration-tests/js-compute/fixtures/tla/src/hello-world.js
- integration-tests/js-compute/fixtures/tla/src/index.js
- integration-tests/js-compute/fixtures/tla/src/routes.js
- integration-tests/js-compute/readme.md
- integration-tests/js-compute/test.js
- package.json
- runtime/fastly/builtins/fastly.cpp
- runtime/fastly/builtins/fetch-event.cpp
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
- test-d/geolocation.test-d.ts
- test-d/globals.test-d.ts
- types/geolocation.d.ts
- types/globals.d.ts
When running in Viceroy, missing geo data causes `len = 0` returns or `none` returns depending on the exact scenario, both of which are currently panics.
This resolves that in returning `null` when no geo data is available. ExecuteD always returns geo data, even if it is mostly stub data, so the test branches on the environment to handle both sides of this correctly.
> Do not panic on missing geo data

- documentation/docs/globals/FetchEvent/FetchEvent.mdx
- integration-tests/js-compute/fixtures/app/src/client.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/fetch-event.cpp
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
- test-d/globals.test-d.ts
- types/globals.d.ts
This is a follow-on to https://github.com/fastly/js-compute-runtime/pull/976 (and is based to), that resolves https://github.com/fastly/js-compute-runtime/issues/753 in always returning `null` instead of throwing an error for missing client data.
Documentation updates are included as well including a note that the null return is for Viceroy / testing environments.
> fix: never error for missing client data, return null instead

- integration-tests/cli/invalid.test.js
- integration-tests/js-compute/fixtures/app/src/cache-simple.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/cache-simple.cpp
- runtime/fastly/builtins/cache-simple.h
This resolves https://github.com/fastly/js-compute-runtime/issues/777 in ensuring that inner promise rejections for `SimpleCache.getOrSet` will reject the outer operation promise.
> fix: simple cache getOrSet inner rejections to reject outer promise

- integration-tests/js-compute/fixtures/app/src/dynamic-backend.js
- runtime/fastly/builtins/backend.cpp
This resolves an issue with the latest release where the dynamic backends refactoring stopped enabling the SSL flag when we know it should be using SSL for dynamically constructed backends.
Includes a test, thanks to the new dynamic backend hostcall support.
> fix: set SSL properly for created dynamic backends

- .github/workflows/release-please.yml
- documentation/app/package-lock.json
- documentation/app/package.json
This fixes our docs deployment to use the crate for `compute-file-server-cli` since `@jakechampion/c-at-e-file-server`  has been yanked from npm.
Necessary to get our 3.27 release working for now, pending further migration from this tool.
> docs: fixup compute-file-server-cli dependency build

- documentation/docs/logger/configureConsole.mdx
- integration-tests/js-compute/fixtures/app/src/logger.js
- runtime/fastly/builtins/logger.cpp
- src/bundle.js
- types/logger.d.ts
Adds a new `configureConsole` method to `fastly:logging` to enable configuration of the `console` logging for removing prefixing and supporting stderr output.
In future, it might be nice to support routing console logs to logging endpoints here as well, but that is out of scope for this initial PR.
> feat: configureConsole function for configuring log prefixing and stderr

- runtime/fastly/host-api/host_api.cpp
Removes `uninitialized` from the error cases which is not an error case as that implies the host error fallback path.
> fix: do not throw uninitialized for KV

- tests/wpt-harness/expectations/WebCryptoAPI/idlharness.https.any.js.json
- tests/wpt-harness/expectations/compression/idlharness.https.any.js.json
- tests/wpt-harness/expectations/console/idlharness.any.js.json
- tests/wpt-harness/expectations/encoding/idlharness.any.js.json
- tests/wpt-harness/expectations/hr-time/idlharness.any.js.json
- tests/wpt-harness/post-harness.js
This reinstates some WPT tests that started failing on the recent upgrade paths by ensuring the wpt post-harness utilizes an indirect eval for proper global scoping of the test definitions.
> fix: reinstate broken wpt tests

- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/fetch/request-response.cpp
- tests/wpt-harness/expectations/fetch/api/request/request-consume-empty.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-consume.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-disturbed.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-headers.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-init-contenttype.any.js.json
- tests/wpt-harness/expectations/fetch/api/request/request-structure.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-consume-empty.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-error-from-stream.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-init-contenttype.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-1.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-2.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-3.any.js.json
- tests/wpt-harness/expectations/fetch/api/response/response-stream-disturbed-4.any.js.json
This adds support for `request.blob`, `response.blob` and supporting `fetch(blob)`, using the new StarlingMonkey blob support.
Unfortunately, the `fetch(blob)` support is currently failing a completely unrelated test even when its codepaths don't apply, so there's an obscure bug here that needs to be investigated further before this can land.
> Fetch blobs

- runtime/fastly/builtins/fastly.cpp
- runtime/fastly/builtins/fetch-event.cpp
- runtime/fastly/builtins/fetch/request-response.cpp
- runtime/fastly/builtins/fetch/request-response.h
- runtime/fastly/host-api/fastly.h
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
This PR updates `createFanoutHandoff()` to call `redirect_to_grip_proxy_v2` instead of `redirect_to_grip_proxy`, passing the Request handle to it.
> Fanout: Use redirect_to_grip_proxy_v2 and pass request handle

- DEVELOPMENT.md
Update development docs:
* Remove outdated steps regarding spidermonkey
* incl. install Python@3 rather than specifically ＠3.11 (as that was a spidermonkey requirement)
* Update build targets: `build`, `build:debug`, `build:weval`
* Added instructions on packing locally to a tarball and installing it to a compute app
> Update development docs

- documentation/docs/kv-store/KVStore/prototype/delete.mdx
- documentation/docs/kv-store/KVStore/prototype/get.mdx
- documentation/docs/kv-store/KVStore/prototype/put.mdx
- integration-tests/js-compute/fixtures/module-mode/src/kv-store.js
- runtime/fastly/builtins/kv-store.cpp
- types/globals.d.ts
- types/kv-store.d.ts
Related:
https://github.com/fastly/cli/issues/1383
https://github.com/fastly/Viceroy/pull/447
Currently the Compute Javascript SDK enforces an incorrect set of special characters that are forbidden in KV key names. The current behavior is forbidding `[`, `]`, `*`, `?`, `#`, while the [documentation](https://docs.fastly.com/en/guides/working-with-kv-stores#limitations-and-considerations) lists `;`, `^`, `|`, `#`, and `?`. Square brackets and asterisks are specifically called out as allowed characters. 
I'm unfamiliar with this codebase, so it's entirely possible I've missed some files that need to be updated.
> Fix forbidden KV key special characters to match documentation

- .github/workflows/main.yml
- .github/workflows/release-please.yml
- DEVELOPMENT.md
- package.json
- tests/wpt-harness/run-wpt.sh
This PR attempts to clean up the build scripts a bit. These changes hope to help people who develop with it.
1. `build` → `build:release` - this builds the 'release' version of the runtime (`fastly.wasm`)
This has been positioned as a sibling to the `build:debug`, `build:debug:info`, and `build:weval` scripts.
The references to the `build` that existed in the following files have been updated:
```
.github/workflows/main.yml
.github/workflows/release-please.yml
tests/wpt-harness/run-wpt.sh
```
2. I've added a `clean` script that cleans out the build artifacts:
```
starling.wasm
fastly.wasm
fastly.debug.wasm
fastly-weval.wasm
fastly-ics.wevalcache
fastly-js-compute-*.tgz
```
3. I've added a new `build` script that calls the `clean` script followed by `build:release`, `build:debug`, and …
> Relabel build scripts and add a 'clean' script

- documentation/docs/kv-store/KVStore/prototype/put.mdx
- integration-tests/js-compute/fixtures/module-mode/src/kv-store.js
- integration-tests/js-compute/fixtures/module-mode/tests.json
- integration-tests/js-compute/setup.js
- runtime/fastly/builtins/kv-store.cpp
- runtime/fastly/host-api/error_numbers.msg
- types/kv-store.d.ts
follow up to https://github.com/fastly/js-compute-runtime/issues/1029
> KV store generation integer follow up (#1029)

- compute-file-server-cli/rust-toolchain.toml
This updates the server toolchain which caused a broken deployment.
> fix: docs server toolchain fix

- types/acl.d.ts
Fixes a typo in the Acl action type definition.
> Acl action type definition typo

- integration-tests/js-compute/setup.js
- runtime/fastly/host-api/host_api.cpp
This fixes a bug found by @harmony7 in https://github.com/harmony7/compute-react19-readablestream-repro where a specific setup in async tasks with immediate timers would lead to a panic.
The panic in this case turns out to be in the Fastly event loop layer, where I previously implemented a bug in the optimized immediate handle checking case in not properly looking up the immediate index. The logic fix is self-explanatory for the most part.
Confirmed that with this change the linked repo no longer panics.
> fix: ready-based immediate task indexing

- documentation/docs/acl/Acl/prototype/lookup.mdx
The examples in the types was updated to note that lookups may return empty, but the one in the SDK docs wasn't yet.
> Correct Acl documentation for null lookup

- integration-tests/js-compute/fixtures/app/tests.json
- integration-tests/js-compute/setup.js
- integration-tests/js-compute/teardown.js
- integration-tests/js-compute/test.js
The config store tests were disabled last week in https://github.com/fastly/js-compute-runtime/pull/1136 due to service reliability issues, this reenables them in our test suite.
> test: reenable config store tests

- integration-tests/js-compute/fixtures/module-mode/src/dynamic-backend.js
- integration-tests/js-compute/test.js
- runtime/fastly/builtins/backend.cpp
This fixes the `Backend.prototype.health` definition which was supposed to be available as a method, and is documented as such, but the `backend.health()` method was not actually being registered or tested.
This fixes and adds a test for the method form (as opposed to the state method form).
> fix: Backend.prototype.health method definition

- types/globals.d.ts
Adding type declarations for Event and EventTarget
So now you can do this:
```typescript
const eventTargetTest = new Promise<string>(resolve => {
class FooEvent extends Event {
constructor(value: string) {
super('foo');
this.value = value;
}
readonly value: string;
}
const eventTarget = new EventTarget();
eventTarget.addEventListener('foo', (event) => {
resolve((event as FooEvent).value);
});
setTimeout(() => {
eventTarget.dispatchEvent(new FooEvent('event-target-test'));
}, 1000);
});
const eventTargetTestValue = await eventTargetTest;
```
> TypeScript type definitions for Event and EventTarget

- types/globals.d.ts
This PR adds TypeScript typings for Blob, File, and FormData so they can be used in Compute apps in TypeScript.
Now tsc is happy with all this:
```typescript
if (event.request.headers.get('content-type')?.startsWith('multipart/form-data')) {
const reqFormData = await event.request.formData();
reqFormData.forEach((value, key) => {
console.log(key, value);
});
}
const file = new File(['hello, world'], 'temp.txt', {
type: 'text/plain'
});
const formData = new FormData();
formData.set('foo', '0');
formData.set('bar', 'doo');
formData.set('baz', file);
const resp = await fetch(
'https://httpbin.org/anything', {
method: 'POST',
body: formData,
backend: 'httpbin',
},
);
```
> TypeScript type definitions for Blob, File, FormData

- types/acl.d.ts
This is a quick fix of the types declaration fix `acl.d.ts` to fix this error
```
% npm run build
> prebuild
> tsc
node_modules/@fastly/js-compute/types/acl.d.ts:8:12 - error TS7010: 'open', which lacks return-type annotation, implicitly has an 'any' return type.
8     static open(aclName: string);
~~~~
Found 1 error in node_modules/@fastly/js-compute/types/acl.d.ts:8
```
> fix: TypeScript declaration return type of Acl.open()

- integration-tests/js-compute/fixtures/module-mode/tests.json
- integration-tests/js-compute/setup.js
- integration-tests/js-compute/teardown.js
Acl tests were disabled last week due to some unexpected service level errors.
In addition the KV Stores aren't properly clearing on our CI runs resulting in limits being reached.
Will debug both of these issues in this PR before landing the stability fixes.
> Reenable acl tests, ci stability fixes

- documentation/docs/config-store/ConfigStore/ConfigStore.mdx
- documentation/docs/dictionary/Dictionary/Dictionary.mdx
- documentation/docs/globals/fetch.mdx
- documentation/docs/kv-store/KVStore/KVStore.mdx
- documentation/docs/secret-store/SecretStore/SecretStore.mdx
https://github.com/fastly/js-compute-runtime/issues/1160
> fix: config store documentation fix (#1160)

- documentation/docs/websocket/createWebsocketHandoff.mdx
- documentation/rename-docs.mjs
- integration-tests/js-compute/fixtures/app/src/index.js
- integration-tests/js-compute/fixtures/app/src/websocket.js
- integration-tests/js-compute/fixtures/app/tests.json
- runtime/fastly/builtins/fastly.cpp
- runtime/fastly/builtins/fastly.h
- runtime/fastly/builtins/fetch-event.cpp
- runtime/fastly/builtins/fetch/request-response.cpp
- runtime/fastly/builtins/fetch/request-response.h
- runtime/fastly/host-api/fastly.h
- runtime/fastly/host-api/host_api.cpp
- runtime/fastly/host-api/host_api_fastly.h
- src/bundle.js
- test-d/websocket.test-d.ts
- types/index.d.ts
- types/websocket.d.ts
This PR adds support for websocket passthrough. https://www.fastly.com/documentation/guides/concepts/real-time-messaging/websockets-tunnel/
Below is sample code for this. Please note that enabling websocket passthrough is required in advance. (e.g.`$fastly products --enable=websockets`).
```
import { createWebsocketHandoff } from "fastly:websocket";
async function handleRequest(event) {
const url = new URL(event.request.url);
if (url.pathname === '/stream') {
return createWebsocketHandoff(event.request, 'websocket_backend');
} else {
return new Response('oopsie, make a request to /stream for some websocket goodies', { status: 404 });
}
}
addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));
```
> feat: add support for Websocket passthrough

- integration-tests/js-compute/fixtures/app/src/assertions.js
- integration-tests/js-compute/fixtures/app/src/compute.js
Fixes and tweaks for the get-vcpu-ms test, which was failing in CI for the unrelated #1182.
- **Use more verbose failure in get-vcpu-ms test**, so we know which assertion failed
- **Formatting fixes**, because I don't know JS style
- **Fix spacing around truthy debug message**, because it put the space in the wrong place
- **Weaken assertion around vCPU startup time: >=0, not >0**, because apparently the runtime's startup is so good now that this assertion fails
> Fixes to vCPU-ms test

- documentation/app/c-at-e-file-server.js
- documentation/app/src/index.js
Update comments to say "KV Store" instead of "Object Store", and remove an `ObjectStore` polyfill in documentation/app/src/index.js that's no longer needed.
> Update comments for Object Store being renamed to KV Store
